"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "VN" | "EN" | "KR" | "CN" | "RU";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    VN: {
        'h-eyebrow': 'Luxury Nail Studio · Đà Nẵng',
        'h-sub': 'Service Menu · Bảng Dịch Vụ',
        's-muse-title': 'Làm móng tay & chân',
        's-muse-sub': 'Chăm sóc móng cơ bản',
        'h-quote': 'Nghệ thuật bắt nguồn từ sự <span>tận tâm</span>. Chúng tôi không chỉ thiết kế móng; chúng tôi trân trọng câu chuyện của bạn.',
        'h-scroll': 'Cuộn xuống',
        's1-title': 'Nail', 's1-sub': 'Dịch vụ móng tay',
        's2-title': 'Pedicure', 's2-sub': 'Chăm sóc móng chân',
        's3-title': 'Add-On', 's3-sub': 'Dịch vụ bổ sung',
        's4-title': 'Hair & Scalp', 's4-sub': 'Gội đầu dưỡng sinh',
        'g-manicure': 'Manicure · Chăm sóc móng',
        'g-enhance': 'Nail Enhancements · Đắp móng',
        'g-art': 'Nail Art',
        'art-note': 'Giá chưa bao gồm sơn gel · Gel polish not included',
        'n-classic-vi': 'Chăm sóc móng cơ bản', 'd-classic': 'Cắt tỉa, dũa móng, chăm sóc da khóe, khăn nóng, thoa kem tay.',
        'n-deluxemani-vi': 'Chăm sóc móng cao cấp', 'd-deluxemani': 'Cắt tỉa, dũa móng, chăm sóc da khóe, gel mặt nạ làm mát, massage tay với kem dưỡng.',
        'n-regpol-vi': 'Sơn thường', 'n-gelpol-vi': 'Sơn gel',
        'n-gelx-vi': 'Uốn móng Gel-X', 'n-buildergel-vi': 'Đắp gel / Tap gel',
        'n-acrylic-vi': 'Đắp bột Acrylic', 'n-refill-vi': 'Bảo dưỡng Acrylic / Builder Gel',
        'n-dual-vi': 'Đắp Dual Form', 'n-biab-vi': 'Đắp BIAB',
        'n-french-vi': 'French Tip', 'n-ombre-vi': 'Ombre', 'n-chrome-vi': 'Chrome / Crom',
        'n-cateye-vi': 'Cat Eye gel', 'n-minimal-vi': 'Nail Art tối giản',
        'n-3d-vi': 'Nghệ thuật 3D / Đính đá / Charm', 'n-custom-vi': 'Vẽ tay / Thiết kế riêng',
        's-essential-title': 'Thiết kế cơ bản', 's-essential-sub': 'Mẫu cơ bản',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Full French Tip', 'n-full-ombre': 'Full Ombre',
        'n-full-chrome': 'Full Chrome', 'n-full-cateye': 'Full Cat eye',
        's-bespoke-title': 'Thiết kế riêng', 's-bespoke-sub': 'Nâng tầm nghệ thuật',
        's-ritual-title': 'Gội đầu & Thư giãn', 's-ritual-sub': 'Spa Phục Hồi',
        'n-bespoke-items': 'Dịch vụ thiết kế riêng', 'p-on-request': 'Giá theo thiết kế',
        'pu1': '/ móng', 'pu2': '/ móng', 'pu3': '/ móng',
        'n-classpedi-vi': 'Chăm sóc chân cơ bản', 'd-classpedi': 'Ngâm chân thảo dược, chà gót, tẩy da chết, cắt tỉa móng, chăm sóc da khóe, khăn nóng, thoa kem.',
        'n-deluxepedi-vi': 'Chăm sóc chân cao cấp', 'd-deluxepedi': 'Bộ kit 4 bước Deluxe: chăm sóc da khóe, cắt tỉa móng, mặt nạ, massage chân.',
        'n-gelcolor-vi': 'Gel màu', 'n-regcolor-vi': 'Sơn thường',
        'n-remacrylic-vi': 'Tháo Acrylic / Gel-X', 'n-remgel-vi': 'Tháo sơn gel',
        'n-classic30-vi': 'Gội đầu cơ bản', 'd-classic30': 'Massage đầu khô, gội dưỡng sinh bằng dầu thảo dược 2 lần, massage đầu tóc & gội xả thảo dược, massage vùng cổ vai gáy cơ bản.',
        'n-deluxe70-vi': 'Gội đầu thư giãn', 'n-luxury90-vi': 'Gội đầu chuyên sâu',
        'sum-d70-txt': 'Xem quy trình 16 bước', 'sum-l90-txt': 'Xem quy trình 19 bước',
        'ft-tagline': 'Nail Studio · Đà Nẵng',
        'ft-studio-desc': 'Nail — Shampoo — Foot Care Studio',
        'ft-note': 'Giá chưa bao gồm thuế<br>Prices subject to change without notice<br>© REMY MUSE Nail Studio',

        // Footer & Map Section
        'nav-portfolio': 'Bộ Sưu Tập',
        'nav-services': 'Dịch Vụ',
        'nav-editorial': 'Bài Viết',
        'nav-location': 'Vị Trí',
        'nav-privacy': 'Quyền Riêng Tư',
        'ft-rights': 'Đã đăng ký bản quyền',

        'map-visit': 'Đến Với Chúng Tôi',
        'map-desc': 'Một studio làm móng hiện đại tại An Hải, Đà Nẵng.',
        'map-hours': 'Giờ Mở Cửa',
        'map-days': 'Thứ 2 - Chủ Nhật',
        'map-hotline': 'Hotline',
        'map-directions': 'Chỉ Đường',
        'map-hub': 'Vị Trí',
        'map-address': '21 An Nhơn 6, An Hải, Đà Nẵng (ngã tư Phan Bôi x An Nhơn 6)',
        'map-connect': 'Kết nối với chúng tôi',
        'map-open-maps': 'Mở Bản Đồ',

        // Booking & Gallery
        'The Muse Gallery': 'Thư viện The Muse',
        'A curated exhibition of our finest artistry. From timeless French tips to avant-garde 3D floral expressions.': 'Triển lãm là nơi tụi mình chọn lọc những mẫu nail đẹp và ưng ý nhất — từ French tip đơn giản, quen thuộc đến những thiết kế hoa 3D sáng tạo.',
        'Experience': 'Trải nghiệm',
        'Schedule': 'Lịch hẹn',
        'Contact': 'Liên hệ',
        'Reserve': 'Đặt chỗ',
        'Your Session': 'Phiên làm đẹp của bạn',
        'A curated encounter with stillness. No deposit required at this stage.': 'Một cuộc gặp gỡ tĩnh lặng được chuẩn bị kỹ lưỡng. Không yêu cầu đặt cọc ở giai đoạn này.',
        'Phase 0': 'Giai đoạn',
        'Instant Notification': 'Thông báo tức thì',
        'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.': 'Đội ngũ của chúng tôi sẽ được thông báo ngay khi bạn lựa chọn. Đối với các yêu cầu đặc biệt, vui lòng liên hệ với chúng tôi qua điện thoại hoặc chat ở phần bên dưới.',
        'Select': 'Lựa chọn',
        'Artistry': 'Nghệ thuật',
        'Choose your signature experience.': 'Chọn trải nghiệm đặc trưng của bạn.',
        'Preparing the catalog...': 'Đang chuẩn bị danh mục...',
        'The': 'Lịch',
        'Timeline': 'Trình tự',
        'Reserve your preferred arrival window.': 'Đặt khung giờ bạn muốn đến.',
        'Select Time Window': 'Chọn khung giờ',
        'You have selected': 'Bạn đã chọn',
        'at': 'vào lúc',
        'Personal': 'Thông tin',
        'Identifier': 'Cá nhân',
        'Finalize your reservation details.': 'Hoàn tất chi tiết đặt chỗ của bạn.',
        'Your Name': 'Tên của bạn',
        'Enter full name': 'Nhập họ và tên',
        'Phone Number': 'Số điện thoại',
        'Finalizing Reservation...': 'Đang hoàn tất đặt chỗ...',
        'Confirm Atelier Reservation': 'Xác nhận đặt chỗ',
        'Previous Phase': 'Giai đoạn trước',
        'Next Phase': 'Giai đoạn tiếp theo',
        'Success.': 'Thành công.',
        'Your request for': 'Yêu cầu của bạn cho',
        'on': 'vào ngày',
        'has been recorded.': 'đã được ghi nhận.',
        'Finalize Experience': 'Hoàn tất trải nghiệm',
        'Nail Services': 'Dịch vụ Nail',
        'Pedicure': 'Chăm sóc chân',
        'Add-On': 'Dịch vụ thêm',
        'Hair & Scalp': 'Gội đầu dưỡng sinh',
        'Other': 'Khác',
        'Days-Su': 'CN',
        'Days-Mo': 'T2',
        'Days-Tu': 'T3',
        'Days-We': 'T4',
        'Days-Th': 'T5',
        'Days-Fr': 'T6',
        'Days-Sa': 'T7',
        // Services - Names
        'Classic Manicure': 'Chăm sóc móng cơ bản',
        'Regular Polish': 'Sơn thường',
        'Gel Polish': 'Sơn gel',
        'Cat Eye': 'Sơn mắt mèo',
        'Full French Tip': 'French toàn bộ',
        'Full Ombre': 'Ombre toàn bộ',
        'Full Chrome': 'Tráng gương toàn bộ',
        'Full Cat Eye': 'Mắt mèo toàn bộ',
        'Bespoke Artistry': 'Thiết kế riêng',
        'Classic Shampoo': 'Gội đầu cơ bản',
        'Deluxe Shampoo': 'Gội đầu dưỡng sinh',
        'Luxury Shampoo': 'Gội đầu hoàng gia',
        // Services - Descriptions
        'Essential nail care, cuticle work, and shaping.': 'Chăm sóc móng thiết yếu, nhặt da và tạo form.',
        'Standard nail polish application.': 'Sơn móng tay cơ bản.',
        'Long-lasting gel polish.': 'Sơn gel giữ màu lâu phai.',
        'Magnetic cat eye gel effect.': 'Hiệu ứng sơn gel mắt mèo từ tính.',
        'Classic or modern French tips on all nails.': 'Viền móng French cổ điển hoặc hiện đại.',
        'Smooth gradient color transition.': 'Chuyển màu gradient mượt mà.',
        'Metallic chrome finish.': 'Hiệu ứng tráng gương toàn bộ móng.',
        'Intense magnetic cat eye on all nails.': 'Sơn mắt mèo toàn bộ các ngón.',
        'Custom, hand-painted sets tailored to your vision.': 'Mẫu vẽ tay, thiết kế riêng theo yêu cầu.',
        'Standard relaxing hair wash.': 'Gội đầu thư giãn cơ bản.',
        'Deep scalp massage and hair nourishment.': 'Gội đầu kết hợp massage da đầu.',
        'Ultimate relaxation with neck and shoulder massage.': 'Gội đầu thư giãn hoàng gia kết hợp massage cổ vai gáy.',

        // Hero
        'h-title-art': 'The |Art| of',
        'h-title-precision': 'Precision.',
        'h-btn-explore': 'Khám Phá Atelier',
        'h-btn-about': 'Về Chúng Tôi',
        'h-label-atelier': 'Xưởng Nghệ Thuật Số',
        'ed-discover': 'Khám phá sự hoàn hảo',
        'ed-craft': 'Tạo nên dấu ấn cá nhân',
        'ed-book': 'Đặt Lịch Ngay',
        'ed-related': 'Khám phá thêm',

        // CTA
        'cta-title': 'Đặt lịch hẹn.',
        'cta-desc': 'Số lượng lịch hẹn giới hạn trong mùa này tại studio trung tâm của chúng tôi.',
        'cta-btn': 'Đặt Lịch Ngay',

        // Visual Break
        'vb-glass-title': 'Glass Nails',
        'vb-glass-sub': 'Móng thủy tinh',
        'vb-chrome-title': 'Chrome Art',
        'vb-chrome-sub': 'Bạc kim loại',
        'vb-3d-title': '3D · Champagne',
        'vb-3d-sub': 'Vàng sâm panh',

        // Brief Intro
        'intro-text': 'REMY MUSE là một không gian nghệ thuật làm móng hiện đại. Chăm chút trong từng chi tiết. Dành riêng cho bạn.',

        // Testimonials
        'review-role': 'Khách hàng',
        'review-1-quote': '"Làm rất kỹ và sạch. Mình rất hài lòng với bộ móng mới."',
        'review-2-quote': '"Nhân viên nhẹ nhàng, dễ chịu. Không gian rất thư giãn."',
        'review-3-quote': '"Dịch vụ chu đáo, tư vấn nhiệt tình. Sẽ quay lại ủng hộ tiếp."',

        // Catalog
        'catalog-btn': 'Xem Toàn Bộ Menu →',
        'catalog-close': 'Đóng',

        'nav-booking': 'Đặt Lịch',
        's-menu-label': 'Dịch Vụ',
        'vc-trending': 'Xu Hướng',
        'vc-gallery-label': 'Bộ Sưu Tập',
        'vc-gallery-title': 'Thư Viện Thiết Kế',
        'vc-gallery-subtitle': 'Các mẫu thiết kế đơn giản, tinh tế cho ngày thường và dịp đặc biệt.',
        'vc-no-match': 'Không có mẫu nào phù hợp với lựa chọn của bạn.',
        'vc-latest-featured': 'Các tác phẩm nổi bật mới nhất',
        'vc-view-full': 'Xem Toàn Bộ Thư Viện',
        'fa-call': 'Gọi ngay',
        'fa-book': 'Đặt lịch',
        'bp-label': 'Góc Chia Sẻ',
        'bp-title': 'Góc Chia Sẻ',
        'bp-desc': 'Mẹo vặt, xu hướng và ý tưởng đơn giản cho đôi tay của bạn.',
        'bp-trending': 'Nổi Bật',
        'bp-view-all': 'Xem Tất Cả Bài Viết',

        // Booking
        'booking-err-fail': 'Không thể tạo lịch hẹn',

        // Catalog & Booking Missing
        'Infinite Design Matrix': 'Ma Trận Thiết Kế Vô Tận',
        'Scroll to Navigate': 'Cuộn Để Khám Phá',
        'Click to Explore': 'Nhấp Để Khám Phá',
        'Swipe · Tap to Explore': 'Vuốt · Chạm Để Khám Phá',
        'Design Detail': 'Chi Tiết Thiết Kế',
        'File': 'Hồ Sơ',
        'Collection': 'Bộ Sưu Tập',
        'Close': 'Đóng',

        'Glass Nails': 'Nail Thủy Tinh',
        'Chrome Luxe': 'Chrome Sang Trọng',
        'Gold Foil': 'Lá Vàng',
        'Vamp Romantic': 'Vamp Lãng Mạn',
        'Bridal': 'Cô Dâu',
        'Ombre': 'Ombre',
        'Minimalist': 'Tối Giản',
        'Marble Luxe': 'Vân Đá Sang Trọng',
        'Botanical': 'Họa Tiết Thực Vật',
        'Chrome': 'Chrome',
        'Animal Print': 'Họa Tiết Động Vật',
        'Constellation': 'Chòm Sao',
        'Pearl': 'Ngọc Trai',
        'Holographic': 'Holographic',
        'Classic': 'Cổ Điển',
        'Line Art': 'Nghệ Thuật Đường Nét',
        'Coral': 'San Hô',
        'Geometric': 'Hình Học',
        'Crystal': 'Pha Lê',
        'Chain': 'Dây Chuyền',
        'Metallic': 'Ánh Kim',
        'Abstract': 'Trừu Tượng',
        'Aura': 'Aura',
        'Dark Luxe': 'Dark Luxe',

        'Ethereal — No. 01': 'Thanh Tao — No. 01',
        'Gilded — No. 02': 'Mạ Vàng — No. 02',
        'Dust & Gold — No. 03': 'Bụi & Vàng — No. 03',
        'Merlot — No. 04': 'Vang Merlot — No. 04',
        'Petals — No. 05': 'Cánh Hoa — No. 05',
        'Rosé — No. 06': 'Hồng Rượu — No. 06',
        'Ink — No. 07': 'Mực In — No. 07',
        'Verde — No. 08': 'Xanh Lục — No. 08',
        'Fluidity — No. 09': 'Dòng Chảy — No. 09',
        'Sakura — No. 10': 'Hoa Anh Đào — No. 10',
        'Rose Gold — No. 11': 'Vàng Hồng — No. 11',
        'Tortoise — No. 12': 'Đồi Mồi — No. 12',
        'Midnight — No. 13': 'Nửa Đêm — No. 13',
        'Velvet Pearl — No. 14': 'Ngọc Trai Nhung — No. 14',
        'Prism — No. 15': 'Lăng Kính — No. 15',
        'Rouge — No. 16': 'Đỏ Rouge — No. 16',
        'Gilded Veins — No. 17': 'Đường Vân Vàng — No. 17',
        'Sunset — No. 18': 'Hoàng Hôn — No. 18',
        'Slate — No. 19': 'Xám Đậm — No. 19',
        'Champagne — No. 20': 'Champagne — No. 20',
        'Link — No. 21': 'Mắt Xích — No. 21',
        'Tidal — No. 22': 'Thủy Triều — No. 22',
        'Blush Aura — No. 23': 'Hồng Hào — No. 23',
        'Obsidian — No. 24': 'Hắc Diện Thạch — No. 24',

        'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.': 'Nail thạch trong suốt với những gợn sóng chrome lỏng. Thiết kế đặc trưng của REMY MUSE bắt trọn ánh sáng và chuyển động, tạo ra một lớp hoàn thiện tuyệt đẹp, trong veo như thủy tinh thay đổi theo từng cử chỉ.',
        'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.': 'Chrome vàng 24K nguyên chất với phom dáng French. Táo bạo nhưng đầy tinh tế, thiết kế này thể hiện sự sang trọng với hiệu ứng tráng gương thu hút mọi ánh nhìn.',
        'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.': 'Lớp nền nude nhám với những vụn lá vàng được đắp thủ công. Mỗi chiếc móng trở thành một bức tranh nghệ thuật của sự sang trọng tự nhiên, không có thiết kế nào hoàn toàn giống nhau.',
        'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.': 'Màu đỏ rượu tía rực rỡ với họa tiết xoắn vàng và trang sức xếp lớp. Thiết kế lãng mạn, đầy kịch tính này lấy cảm hứng từ tính thẩm mỹ cổ điển pha trộn nét hiện đại của nghệ thuật tạp chí.',
        'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.': 'Chrome ngọc trai với chi tiết hoa 3D nổi. Thiết kế cô dâu được yêu cầu nhiều nhất của chúng tôi, nổi bật với những bông hoa sứ làm thủ công và tâm đính đá vi lê.',
        'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.': 'Hiệu ứng ombre chuyển từ hồng nhạt sang trắng với lá vàng điểm xuyết. Một thiết kế tinh tế, nữ tính, phù hợp hoàn hảo từ ngày thường đến các sự kiện buổi tối.',
        'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.': 'Họa tiết hình học đen sắc sảo trên nền trắng. Lấy cảm hứng từ hội họa hiện đại, thiết kế tối giản này toát lên vẻ tự tin qua từng đường nét chuẩn xác.',
        'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.': 'Màu xanh ngọc lục bảo với những đường kintsugi vẽ tay bằng vàng. Một sự tôn vinh vẻ đẹp của sự không hoàn hảo, lấy cảm hứng từ nghệ thuật sửa chữa đồ gốm bằng vàng của Nhật Bản.',
        'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.': 'Không gian trong suốt với những giọt chrome bạc tan chảy. Một phong cách tiên phong trong nghệ thuật làm móng, đùa giỡn với ranh giới của chất lỏng và hình khối.',
        'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.': 'Nail màu trắng sữa với những cành hoa anh đào vẽ tay. Từng cánh hoa được khắc họa riêng bởi các nghệ nhân chuyên nghiệp, mang đến một tuyệt tác thực vật đậm chất cá nhân.',
        'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.': 'Chrome gương vàng hồng ấm áp cùng họa tiết nhẫn xếp chồng tinh tế. Đỉnh cao của sự sang trọng tối giản, sắc ánh kim này tôn vinh mọi tông da.',
        'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.': 'Họa tiết đồi mồi màu hổ phách với những hạt vụn vàng. Một góc nhìn đầy tinh tế về họa tiết động vật, gợi nhắc đến những món phụ kiện vintage xa xỉ.',
        'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.': 'Màu xanh navy điểm xuyết họa tiết chòm sao vàng vẽ tay. Một thiết kế bầu trời mang những vì sao lên đầu ngón tay với độ chính xác chuẩn thiên văn.',
        'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.': 'Màu hồng phấn nhám mịn tựa nhung đính ngọc trai tinh tế. Mềm mại, kích thích xúc giác và nữ tính khó cưỡng - tựa như khoác lụa lên móng tay.',
        'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.': 'Chrome holographic đa sắc bắt trọn mọi sắc cầu vồng. Một thiết kế đậm chất tương lai, đầy ấn tượng dành cho những tâm hồn cá tính.',
        'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.': 'Màu đỏ sẫm vượt thời gian kết hợp họa tiết nửa vầng trăng vàng ở chân móng. Một sự diễn giải hiện đại về phong cách làm móng quyến rũ kinh điển của Hollywood.',
        'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.': 'Nền hồng nude với những nét vẽ vàng mảnh – vòng xoáy tinh tế và hạt siêu nhỏ. Lấy cảm hứng từ những đường vân khoáng chất tự nhiên, một thiết kế nhẹ nhàng nhưng vô cùng cầu kỳ.',
        'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.': 'Màu san hô ấm áp điểm xuyết vụn vàng lá. Một thiết kế mang hơi thở của nắng, tràn đầy năng lượng và ấm áp, hoàn hảo cho những buổi tối mùa hè.',
        'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.': 'Xám đậm nhám kết hợp họa tiết hình học chrome bạc. Những đường nét sắc sảo, cấu trúc gặp gỡ sắc xám êm dịu, tạo nên vẻ đẹp đô thị hiện đại.',
        'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.': 'Nhũ vàng lấp lánh đính pha lê Swarovski. Mẫu móng tiệc tùng đỉnh cao — thiết kế riêng cho những khoảnh khắc cần sự lộng lẫy nhất.',
        'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.': 'Màu tím tro đính điểm nhấn dây xích vàng 3D. Một tuyên ngôn thời trang táo bạo, thu hẹp khoảng cách giữa nghệ thuật làm móng và trang sức.',
        'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.': 'Nền xanh cổ vịt với họa tiết sóng chrome bạc. Mềm mại và sống động, thiết kế này tái hiện lại nhịp sóng biển dưới hình thái ánh kim.',
        'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.': 'Hiệu ứng gradient aura lan tỏa nhẹ nhàng giữa sắc đào và hồng cánh sen. Một thiết kế lấp lánh mang tính tâm linh sâu sắc, mô phỏng lại những trường năng lượng thanh tao của cơ thể.',
        'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.': 'Đen nhám với họa tiết hình học đính đinh tán vàng. Mạnh mẽ, tự tin và táo bạo đến kiêu ngạo - dành riêng cho những ai luôn làm chủ mọi ánh nhìn.',
    },
    EN: {
        'h-eyebrow': 'Luxury Nail Studio · Da Nang',
        'h-sub': 'Service Menu',
        's-muse-title': 'Manicure & Pedicure',
        's-muse-sub': 'Basic nail care',
        'h-quote': 'Artistry inspired by <span>care</span>. We don’t just design nails; we cherish your story.',
        'h-scroll': 'Scroll',
        's1-title': 'Nail Services', 's1-sub': 'Nail Care',
        's2-title': 'Pedicure', 's2-sub': 'Foot Care',
        's3-title': 'Add-On', 's3-sub': 'Optional Extras',
        's4-title': 'Hair & Scalp', 's4-sub': 'Herbal Shampoo',
        'g-manicure': 'Manicure', 'g-enhance': 'Nail Enhancements', 'g-art': 'Nail Art',
        'art-note': 'Gel polish not included in Nail Art prices',
        'n-classic-vi': 'Classic Manicure', 'd-classic': 'Nail trimming & shaping, cuticle grooming, hot towel, cream hand application.',
        'n-deluxemani-vi': 'Deluxe Manicure', 'd-deluxemani': 'Nail trimming & shaping, cuticle grooming, cooling gel mask, hand massage with cream.',
        'n-regpol-vi': 'Regular Polish', 'n-gelpol-vi': 'Gel Polish',
        'n-gelx-vi': 'Gel-X Full Set', 'n-buildergel-vi': 'Builder Gel Full Set',
        'n-acrylic-vi': 'Acrylic Full Set', 'n-refill-vi': 'Acrylic / Builder Gel Refill',
        'n-dual-vi': 'Dual Form Full Set', 'n-biab-vi': 'BIAB Overlay',
        'n-french-vi': 'French Tip', 'n-ombre-vi': 'Ombre', 'n-chrome-vi': 'Chrome Powder',
        'n-cateye-vi': 'Cat Eye', 'n-minimal-vi': 'Minimal Nail Art',
        'n-3d-vi': '3D Art / Rhinestone / Charm', 'n-custom-vi': 'Custom / Hand-Painted Design',
        's-essential-title': 'Basic Designs', 's-essential-sub': 'Core Artistry',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Full French Tip', 'n-full-ombre': 'Full Ombre',
        'n-full-chrome': 'Full Chrome', 'n-full-cateye': 'Full Cat Eye',
        's-bespoke-title': 'Custom Design', 's-bespoke-sub': 'Elevated Artistry',
        's-ritual-title': 'Hair shampoo & Relaxation', 's-ritual-sub': 'Restorative Spa',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': 'Price on request',
        'pu1': '/ nail', 'pu2': '/ nail', 'pu3': '/ nail',
        'n-classpedi-vi': 'Classic Pedicure', 'd-classpedi': 'Herbal foot soak, heel scrub, exfoliation, nail trimming, cuticle grooming, hot towel, cream.',
        'n-deluxepedi-vi': 'Deluxe Pedicure', 'd-deluxepedi': '4-step deluxe kit: cuticle care, trimming, mask, foot massage.',
        'n-gelcolor-vi': 'Gel Color', 'n-regcolor-vi': 'Regular Color',
        'n-remacrylic-vi': 'Acrylic / Gel-X Removal', 'n-remgel-vi': 'Gel Color Removal',
        'n-classic30-vi': 'Classic Shampoo', 'd-classic30': 'Dry scalp massage, double herbal shampoo, herbal conditioner massage, basic neck & shoulder massage.',
        'n-deluxe70-vi': 'Deluxe Shampoo', 'n-luxury90-vi': 'Luxury Shampoo',
        'sum-d70-txt': 'View 16-step process', 'sum-l90-txt': 'View 19-step process',
        'ft-tagline': 'Nail Studio · Da Nang',
        'ft-note': 'Prices exclusive of tax<br>Subject to change without notice<br>© REMY MUSE Nail Studio',

        // Footer & Map Section
        'nav-portfolio': 'Portfolio',
        'nav-services': 'Services',
        'nav-editorial': 'Editorial',
        'nav-location': 'Location',
        'nav-privacy': 'Privacy',
        'ft-rights': 'All rights reserved',

        'map-visit': 'Visit Us',
        'map-desc': 'A modern nail studio in An Hai, Da Nang.',
        'map-hours': 'Opening Hours',
        'map-days': 'Mon - Sun',
        'map-hotline': 'Direct Line',
        'map-directions': 'Get Directions',
        'map-hub': 'Aesthetic Hub',
        'map-address': '21 An Nhon 6, An Hai, Da Nang (Phan Boi x An Nhon 6 intersection)',
        'map-connect': 'Connect with us',
        'map-open-maps': 'Open in Maps',
        // Booking & Gallery Base EN
        'The Muse Gallery': 'The Muse Gallery',
        'A curated exhibition of our finest artistry. From timeless French tips to avant-garde 3D floral expressions.': 'A curated space where we select the most beautiful and satisfying nail designs — from simple, classic French tips to creative 3D floral expressions.',
        'Experience': 'Experience',
        'Schedule': 'Schedule',
        'Contact': 'Contact',
        'Reserve': 'Reserve',
        'Your Session': 'Your Session',
        'A curated encounter with stillness. No deposit required at this stage.': 'A curated encounter with stillness. No deposit required at this stage.',
        'Phase 0': 'Phase 0',
        'Instant Notification': 'Instant Notification',
        'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.': 'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.',
        'Select': 'Select',
        'Artistry': 'Artistry',
        'Choose your signature experience.': 'Choose your signature experience.',
        'Preparing the catalog...': 'Preparing the catalog...',
        'The': 'The',
        'Timeline': 'Timeline',
        'Reserve your preferred arrival window.': 'Reserve your preferred arrival window.',
        'Select Time Window': 'Select Time Window',
        'You have selected': 'You have selected',
        'at': 'at',
        'Personal': 'Personal',
        'Identifier': 'Identifier',
        'Finalize your reservation details.': 'Finalize your reservation details.',
        'Your Name': 'Your Name',
        'Enter full name': 'Enter full name',
        'Phone Number': 'Phone Number',
        'Finalizing Reservation...': 'Finalizing Reservation...',
        'Confirm Atelier Reservation': 'Confirm Atelier Reservation',
        'Previous Phase': 'Previous Phase',
        'Next Phase': 'Next Phase',
        'Success.': 'Success.',
        'Your request for': 'Your request for',
        'on': 'on',
        'has been recorded.': 'has been recorded.',
        'Finalize Experience': 'Finalize Experience',
        // Services - Names
        'Classic Manicure': 'Classic Manicure',
        'Regular Polish': 'Regular Polish',
        'Gel Polish': 'Gel Polish',
        'Cat Eye': 'Cat Eye',
        'Full French Tip': 'Full French Tip',
        'Full Ombre': 'Full Ombre',
        'Full Chrome': 'Full Chrome',
        'Full Cat Eye': 'Full Cat Eye',
        'Bespoke Artistry': 'Bespoke Artistry',
        'Classic Shampoo': 'Classic Shampoo',
        'Deluxe Shampoo': 'Deluxe Shampoo',
        'Luxury Shampoo': 'Luxury Shampoo',
        // Services - Descriptions
        'Essential nail care, cuticle work, and shaping.': 'Essential nail care, cuticle work, and shaping.',
        'Standard nail polish application.': 'Standard nail polish application.',
        'Long-lasting gel polish.': 'Long-lasting gel polish.',
        'Magnetic cat eye gel effect.': 'Magnetic cat eye gel effect.',
        'Classic or modern French tips on all nails.': 'Classic or modern French tips on all nails.',
        'Smooth gradient color transition.': 'Smooth gradient color transition.',
        'Metallic chrome finish.': 'Metallic chrome finish.',
        'Intense magnetic cat eye on all nails.': 'Intense magnetic cat eye on all nails.',
        'Custom, hand-painted sets tailored to your vision.': 'Custom, hand-painted sets tailored to your vision.',
        'Standard relaxing hair wash.': 'Standard relaxing hair wash.',
        'Deep scalp massage and hair nourishment.': 'Deep scalp massage and hair nourishment.',
        'Ultimate relaxation with neck and shoulder massage.': 'Ultimate relaxation with neck and shoulder massage.',
        'Other': 'Other',
        'Nail Services': 'Nail Services',
        'Pedicure': 'Pedicure',
        'Add-On': 'Add-On',
        'Hair & Scalp': 'Hair & Scalp',
        'Days-Su': 'Su',
        'Days-Mo': 'Mo',
        'Days-Tu': 'Tu',
        'Days-We': 'We',
        'Days-Th': 'Th',
        'Days-Fr': 'Fr',
        'Days-Sa': 'Sa',
        'Infinite Design Matrix': 'Infinite Design Matrix',
        'Scroll to Navigate': 'Scroll to Navigate',
        'Click to Explore': 'Click to Explore',
        'Swipe · Tap to Explore': 'Swipe · Tap to Explore',
        'Design Detail': 'Design Detail',
        'File': 'File',
        'Collection': 'Collection',
        'Close': 'Close',
        'Glass Nails': 'Glass Nails',
        'Chrome Luxe': 'Chrome Luxe',
        'Gold Foil': 'Gold Foil',
        'Vamp Romantic': 'Vamp Romantic',
        'Bridal': 'Bridal',
        'Ombre': 'Ombre',
        'Minimalist': 'Minimalist',
        'Marble Luxe': 'Marble Luxe',
        'Botanical': 'Botanical',
        'Chrome': 'Chrome',
        'Animal Print': 'Animal Print',
        'Constellation': 'Constellation',
        'Pearl': 'Pearl',
        'Holographic': 'Holographic',
        'Classic': 'Classic',
        'Line Art': 'Line Art',
        'Coral': 'Coral',
        'Geometric': 'Geometric',
        'Crystal': 'Crystal',
        'Chain': 'Chain',
        'Metallic': 'Metallic',
        'Abstract': 'Abstract',
        'Aura': 'Aura',
        'Dark Luxe': 'Dark Luxe',
        'Ethereal — No. 01': 'Ethereal — No. 01',
        'Gilded — No. 02': 'Gilded — No. 02',
        'Dust & Gold — No. 03': 'Dust & Gold — No. 03',
        'Merlot — No. 04': 'Merlot — No. 04',
        'Petals — No. 05': 'Petals — No. 05',
        'Rosé — No. 06': 'Rosé — No. 06',
        'Ink — No. 07': 'Ink — No. 07',
        'Verde — No. 08': 'Verde — No. 08',
        'Fluidity — No. 09': 'Fluidity — No. 09',
        'Sakura — No. 10': 'Sakura — No. 10',
        'Rose Gold — No. 11': 'Rose Gold — No. 11',
        'Tortoise — No. 12': 'Tortoise — No. 12',
        'Midnight — No. 13': 'Midnight — No. 13',
        'Velvet Pearl — No. 14': 'Velvet Pearl — No. 14',
        'Prism — No. 15': 'Prism — No. 15',
        'Rouge — No. 16': 'Rouge — No. 16',
        'Gilded Veins — No. 17': 'Gilded Veins — No. 17',
        'Sunset — No. 18': 'Sunset — No. 18',
        'Slate — No. 19': 'Slate — No. 19',
        'Champagne — No. 20': 'Champagne — No. 20',
        'Link — No. 21': 'Link — No. 21',
        'Tidal — No. 22': 'Tidal — No. 22',
        'Blush Aura — No. 23': 'Blush Aura — No. 23',
        'Obsidian — No. 24': 'Obsidian — No. 24',
        'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.': 'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.',
        'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.': 'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.',
        'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.': 'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.',
        'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.': 'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.',
        'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.': 'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.',
        'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.': 'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.',
        'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.': 'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.',
        'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.': 'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.',
        'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.': 'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.',
        'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.': 'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.',
        'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.': 'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.',
        'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.': 'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.',
        'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.': 'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.',
        'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.': 'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.',
        'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.': 'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.',
        'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.': 'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.',
        'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.': 'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.',
        'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.': 'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.',
        'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.': 'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.',
        'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.': 'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.',
        'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.': 'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.',
        'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.': 'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.',
        'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.': 'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.',
        'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.': 'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.',

        // Hero
        'h-title-art': 'The |Art| of',
        'h-title-precision': 'Precision.',
        'h-btn-explore': 'Explore Atelier',
        'h-btn-about': 'About Us',
        'h-label-atelier': 'Digital Atelier',
        'ed-discover': 'Discover Perfection',
        'ed-craft': 'Craft your identity',
        'ed-book': 'Book Your Session',
        'ed-related': 'Related Insights',

        // CTA
        'cta-title': 'Book your appointment.',
        'cta-desc': 'Limited appointments available for the upcoming season at our downtown studio.',
        'cta-btn': 'Reserve Appointment',

        // Visual Break
        'vb-glass-title': 'Glass Nails',
        'vb-glass-sub': 'Glass effect',
        'vb-chrome-title': 'Chrome Art',
        'vb-chrome-sub': 'Metallic silver',
        'vb-3d-title': '3D · Champagne',
        'vb-3d-sub': 'Champagne gold',

        // Brief Intro
        'intro-text': 'REMY MUSE is a modern nail studio. Crafted with intention. Designed for you.',

        // Testimonials
        'review-role': 'Client',
        'review-1-quote': '"Meticulous and clean work. I am very satisfied with my new nails."',
        'review-2-quote': '"Gentle and pleasant staff. The atmosphere is very relaxing."',
        'review-3-quote': '"Attentive service, enthusiastic consultation. I will definitely come back."',

        // Catalog
        'catalog-btn': 'View Full Menu →',
        'catalog-close': 'Close',

        'nav-booking': 'Booking',
        's-menu-label': 'Our Services',
        'vc-trending': 'Trending',
        'vc-gallery-label': 'Portfolio',
        'vc-gallery-title': 'The Portfolio',
        'vc-gallery-subtitle': 'Simple, clean designs for everyday and special moments.',
        'vc-no-match': 'No designs match your selection.',
        'vc-latest-featured': 'Latest featured works',
        'vc-view-full': 'View Full Gallery',
        'fa-call': 'Call us',
        'fa-book': 'Book now',
        'bp-label': 'Insights',
        'bp-title': 'Insights',
        'bp-desc': 'Simple tips, trends, and ideas for your nails.',
        'bp-trending': "Editor's Pick",
        'bp-view-all': 'Explore Full Library',

        // Booking
        'ft-studio-desc': 'Nail — Shampoo — Foot Care Studio',
        'booking-err-fail': 'Failed to create booking',
    },
    KR: {
        'h-eyebrow': '럭셔리 네일 스튜디오 · 다낭',
        'h-sub': '서비스 메뉴',
        's-muse-title': '매니큐어 & 페디큐어',
        's-muse-sub': '기본 네일 케어',
        'h-quote': '예술성은 <span>정성</span>에서 시작됩니다. 우리는 단순한 네일 디자인을 넘어, 당신의 이야기를 소중히 담아냅니다.',
        'h-scroll': '스크롤',
        's1-title': '네일 서비스', 's1-sub': '네일 케어',
        's2-title': '페디큐어', 's2-sub': '발 관리',
        's3-title': '추가 서비스', 's3-sub': '옵션',
        's4-title': '헤어 & 두피', 's4-sub': '허브 샴푸',
        'g-manicure': '매니큐어', 'g-enhance': '네일 연장', 'g-art': '네일 아트',
        'art-note': '네일 아트 가격에 젤 폴리시는 미포함',
        'n-classic-vi': '클래식 매니큐어', 'd-classic': '손톱 정리·모양잡기, 큐티클 케어, 핫 타월, 핸드크림.',
        'n-deluxemani-vi': '디럭스 매니큐어', 'd-deluxemani': '손톱 정리·모양잡기, 큐티클 케어, 쿨링 젤 마스크, 핸드 마사지.',
        'n-regpol-vi': '일반 폴리시', 'n-gelpol-vi': '젤 폴리시',
        'n-gelx-vi': 'Gel-X 풀세트', 'n-buildergel-vi': '빌더 젤 풀세트',
        'n-acrylic-vi': '아크릴 풀세트', 'n-refill-vi': '아크릴/빌더젤 리필',
        'n-dual-vi': '듀얼 폼 풀세트', 'n-biab-vi': 'BIAB 오버레이',
        'n-french-vi': '프렌치 팁', 'n-ombre-vi': '옴브레', 'n-chrome-vi': '크롬 파우더',
        'n-cateye-vi': '캣아이', 'n-minimal-vi': '미니멀 아트',
        'n-3d-vi': '3D아트/라인스톤/참', 'n-custom-vi': '커스텀/핸드페인팅',
        's-essential-title': '베이직 디자인', 's-essential-sub': '코어 네일 아트',
        'n-essential-items': '풀 프렌치 팁 / 옴브레 / 크롬 / 캣아이',
        'n-full-french': '풀 프렌치 팁 (Full French Tip)', 'n-full-ombre': '풀 옴브레 (Full Ombre)',
        'n-full-chrome': '풀 크롬 (Full Chrome)', 'n-full-cateye': '풀 캣아이 (Full Cat Eye)',
        's-bespoke-title': '커스텀 디자인', 's-bespoke-sub': '커스텀 아트',
        'n-bespoke-items': '당신의 비전에 맞춘 커스텀 핸드 페인팅 세트',
        's-ritual-title': '헤어 샴푸 & 릴랙세이션', 's-ritual-sub': '복구 스파',
        'p-on-request': '디자인별 별도 문의',
        'pu1': '/ 손가락', 'pu2': '/ 손가락', 'pu3': '/ 손가락',
        'n-classpedi-vi': '클래식 페디큐어', 'd-classpedi': '허브 족욕, 굳은살 제거, 각질 제거, 손발톱 정리, 큐티클 케어, 핫 타월, 크림.',
        'n-deluxepedi-vi': '디럭스 페디큐어', 'd-deluxepedi': '4단계 디럭스 키트: 큐티클 케어, 정리, 마스크, 발 마사지.',
        'n-gelcolor-vi': '젤 컬러', 'n-regcolor-vi': '일반 컬러',
        'n-remacrylic-vi': '아크릴/Gel-X 제거', 'n-remgel-vi': '젤 컬러 제거',
        'n-classic30-vi': '클래식 샴푸', 'd-classic30': '드라이 두피 마사지, 허브 오일 샴푸 2회, 허브 컨디셔너 마사지, 기본 목·어깨 마사지.',
        'n-deluxe70-vi': '디럭스 샴푸', 'n-luxury90-vi': '럭셔리 샴푸',
        'sum-d70-txt': '16단계 과정 보기', 'sum-l90-txt': '19단계 과정 보기',
        'ft-tagline': 'Nail Studio · 다낭',
        'ft-note': '가격은 세금 미포함<br>사전 공지 없이 변경 가능<br>© REMY MUSE Nail Studio',

        // Footer & Map Section
        'nav-portfolio': '포트폴리오',
        'nav-services': '서비스',
        'nav-editorial': '에디토리얼',
        'nav-location': '위치',
        'nav-privacy': '개인정보보호',
        'ft-rights': '모든 권리 보유',

        'map-visit': '방문하기',
        'map-desc': '다낭 안하이에 위치한 모던 네일 스튜디오.',
        'map-hours': '영업 시간',
        'map-days': '월 - 일',
        'map-hotline': '직통 전화',
        'map-directions': '길찾기',
        'map-hub': '미학 허브',
        'map-address': '다낭 안하이 21 An Nhon 6 (판보이 x 안논 6 교차로)',
        'map-connect': '우리와 연결',
        'map-open-maps': '지도에서 열기',
        // Booking & Gallery
        'The Muse Gallery': '더 뮤즈 갤러리',
        'A curated exhibition of our finest artistry. From timeless French tips to avant-garde 3D floral expressions.': '가장 아름답고 만족스러운 네일 디자인을 엄선한 전시 공간입니다 — 심플하고 익숙한 프렌치 팁부터 창의적인 3D 플로럴 디자인까지.',
        'Experience': '경험',
        'Schedule': '예약',
        'Contact': '문의',
        'Reserve': '예약하기',
        'Your Session': '당신의 세션',
        'A curated encounter with stillness. No deposit required at this stage.': '정적과의 엄선된 만남. 현재 단계에서는 보증금이 필요하지 않습니다.',
        'Phase 0': '단계 0',
        'Instant Notification': '즉시 알림',
        'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.': '선택 즉시 아뜰리에 팀에게 알림이 전송됩니다. 특정 요청 사항이 있으시면 아래 섹션의 전화나 채팅을 통해 문의해 주세요.',
        'Select': '선택',
        'Artistry': '예술성',
        'Choose your signature experience.': '당신만의 시그니처 경험을 선택하세요.',
        'Preparing the catalog...': '카탈로그 준비 중...',
        'The': '',
        'Timeline': '타임라인',
        'Reserve your preferred arrival window.': '원하시는 도착 시간대를 예약하세요.',
        'Select Time Window': '시간대 선택',
        'You have selected': '다음을 선택하셨습니다',
        'at': '시각:',
        'Personal': '개인',
        'Identifier': '식별자',
        'Finalize your reservation details.': '예약 세부 사항을 마무리하세요.',
        'Your Name': '성함',
        'Enter full name': '성함을 입력하세요',
        'Phone Number': '전화번호',
        'Finalizing Reservation...': '예약 마무리 중...',
        'Confirm Atelier Reservation': '아뜰리에 예약 확정',
        'Previous Phase': '이전 단계',
        'Next Phase': '다음 단계',
        'Success.': '성공.',
        'Your request for': '선택하신 서비스 ',
        'on': ' 일시: ',
        'has been recorded.': ' 예약 신청이 정상적으로 접수되었습니다.',
        'Finalize Experience': '경험 마무리하기',
        'Other': '기타',
        'Nail Services': '네일 서비스',
        'Pedicure': '페디큐어',
        'Add-On': '추가 서비스',
        'Hair & Scalp': '헤어 & 두피',
        'Days-Su': '일',
        'Days-Mo': '월',
        'Days-Tu': '화',
        'Days-We': '수',
        'Days-Th': '목',
        'Days-Fr': '금',
        'Days-Sa': '토',
        'Infinite Design Matrix': '무한 디자인 매트릭스',
        'Scroll to Navigate': '스크롤하여 이동',
        'Click to Explore': '클릭하여 탐색',
        'Swipe · Tap to Explore': '스와이프 · 탭하여 탐색',
        'Design Detail': '디자인 상세',
        'File': '파일',
        'Collection': '컬렉션',
        'Close': '닫기',
        'Glass Nails': '글래스 네일',
        'Chrome Luxe': '크롬 럭스',
        'Gold Foil': '골드 포일',
        'Vamp Romantic': '뱀프 로맨틱',
        'Bridal': '브라이덜',
        'Ombre': '옴브레',
        'Minimalist': '미니멀리스트',
        'Marble Luxe': '마블 럭스',
        'Botanical': '보태니컬',
        'Chrome': '크롬',
        'Animal Print': '애니멀 프린트',
        'Constellation': '컨스텔레이션',
        'Pearl': '펄',
        'Holographic': '홀로그래픽',
        'Classic': '클래식',
        'Line Art': '라인 아트',
        'Coral': '코랄',
        'Geometric': '지오메트릭',
        'Crystal': '크리스탈',
        'Chain': '체인',
        'Metallic': '메탈릭',
        'Abstract': '앱스트랙트',
        'Aura': '아우라',
        'Dark Luxe': '다크 럭스',
        'Ethereal — No. 01': '에테리얼 — No. 01',
        'Gilded — No. 02': '길디드 — No. 02',
        'Dust & Gold — No. 03': '더스트 & 골드 — No. 03',
        'Merlot — No. 04': '메를로 — No. 04',
        'Petals — No. 05': '페탈 — No. 05',
        'Rosé — No. 06': '로제 — No. 06',
        'Ink — No. 07': '잉크 — No. 07',
        'Verde — No. 08': '베르데 — No. 08',
        'Fluidity — No. 09': '플루이디티 — No. 09',
        'Sakura — No. 10': '사쿠라 — No. 10',
        'Rose Gold — No. 11': '로즈 골드 — No. 11',
        'Tortoise — No. 12': '토터스 — No. 12',
        'Midnight — No. 13': '미드나잇 — No. 13',
        'Velvet Pearl — No. 14': '벨벳 펄 — No. 14',
        'Prism — No. 15': '프리즘 — No. 15',
        'Rouge — No. 16': '루즈 — No. 16',
        'Gilded Veins — No. 17': '길디드 베인 — No. 17',
        'Sunset — No. 18': '선셋 — No. 18',
        'Slate — No. 19': '슬레이트 — No. 19',
        'Champagne — No. 20': '샴페인 — No. 20',
        'Link — No. 21': '링크 — No. 21',
        'Tidal — No. 22': '타이달 — No. 22',
        'Blush Aura — No. 23': '블러쉬 아우라 — No. 23',
        'Obsidian — No. 24': '옵시디언 — No. 24',
        'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.': '리퀴드 크롬 웨이브가 있는 반투명 젤리 네일. 빛과 움직임을 포착하여 몸짓마다 변하는 우아한 유리 같은 피니시를 선사하는 REMY MUSE의 시그니처 디자인입니다.',
        'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.': '프렌치 실루엣이 가미된 순수 24K 골드 크롬. 대담하면서도 세련된 이 디자인은 어떤 환경에서도 시선을 사로잡는 거울 같은 피니시로 화려함을 구현합니다.',
        'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.': '손으로 직접 붙인 금박 조각이 있는 누드 매트 베이스. 각 손톱은 유기적인 럭셔리의 캔버스가 되며, 두 가지 디자인이 똑같을 수 없습니다.',
        'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.': '골드 스월 액센트와 레이어드 주얼리가 있는 딥 버건디. 이 드라마틱하고 로맨틱한 디자인은 빈티지 미학에서 영감을 받아 현대적인 에디토리얼 감각을 더했습니다.',
        'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.': '조각된 3D 플로럴 장식이 있는 펄 크롬. 수작업으로 제작된 포슬린 플라워와 마이크로 크리스탈 센터가 특징인 가장 인기 있는 브라이덜 디자인입니다.',
        'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.': '금박이 흩뿌려진 부드러운 핑크-투-화이트 그라데이션. 낮부터 저녁까지 모든 행사에 매끄럽게 어울리는 섬세하고 여성스러운 디자인입니다.',
        'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.': '깨끗한 화이트 캔버스 위의 대담한 블랙 지오메트릭 라인 아트. 모더니즘 회화에서 영감을 받은 이 미니멀한 디자인은 정교하고 자신감 있는 스트로크를 통해 이야기합니다.',
        'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.': '손으로 그린 골드 킨츠기 베인이 있는 에메랄드 그린. 깨진 도자기를 금으로 수리하는 일본의 예술에서 영감을 받아 불완전함과 아름다움을 찬양합니다.',
        'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.': '유동적인 실버 크롬 드립이 있는 투명한 네거티브 스페이스. 액체와 고체 형태의 경계를 넘나드는 아방가르드한 네일 아트 접근 방식입니다.',
        'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.': '손으로 그린 벚꽃 가지가 있는 밀키 화이트 네일. 각 꽃잎은 마스터 아티스트가 개별적으로 표현하여 진정한 맞춤형 보태니컬 작품을 완성합니다.',
        'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.': '섬세한 스태킹 링이 있는 따뜻한 로즈 골드 미러 크롬. 절제된 럭셔리의 정점을 보여주는 이 메탈릭 피니시는 모든 피부 톤을 돋보이게 합니다.',
        'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.': '골드 마이크로 플렉이 있는 앰버 토터스쉘 패턴. 빈티지 럭셔리 액세서리를 연상시키는 세련된 애니멀 프린트 해석입니다.',
        'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.': '손으로 그린 골드 별자리 패턴이 있는 네이비 블루. 천문학적 정밀함으로 손끝에 별을 담아낸 천상의 디자인입니다.',
        'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.': '섬세한 진주 장식이 있는 블러쉬 핑크 벨벳 매트. 부드럽고 촉감이 좋으며 거부할 수 없을 정도로 여성스럽습니다. 마치 손톱에 실크를 입은 듯한 느낌을 줍니다.',
        'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.': '무지개의 모든 색을 포착하는 풀 스펙트럼 홀로그래픽 크롬. 대담한 분들을 위한 미래지향적이고 시선을 사로잡는 디자인입니다.',
        'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.': '골드 하프문 큐티클 디테일이 있는 시대를 초월한 크림슨 레드. 클래식한 할리우드 글래머 매니큐어를 현대적으로 재해석했습니다.',
        'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.': '미세한 골드 라인 아트(섬세한 스월과 마이크로 도트)가 있는 누드 핑크 베이스. 천연 광물 맥에서 영감을 받은 이 디자인은 미묘하면서도 복잡합니다.',
        'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.': '골드 포일 플레이크 액센트가 있는 따뜻한 코랄. 따뜻함과 활력을 불어넣는 선키스트 디자인으로 여름 저녁에 완벽합니다.',
        'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.': '실버 크롬 지오메트릭 패턴이 있는 매트 슬레이트 그레이. 날카로운 건축적 라인과 부드러운 그레이 톤이 만나 현대적이고 도시적인 미학을 선사합니다.',
        'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.': '스와로브스키 크리스탈이 배치된 골드 글리터. 가장 눈부신 순간을 위해 디자인된 궁극의 셀러브레이션 네일입니다.',
        'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.': '3D 골드 체인 장식이 있는 더스티 모브. 주얼리와 네일 아트의 경계를 허무는 대담하고 패셔너블한 선언입니다.',
        'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.': '실버 크롬 웨이브 패턴이 있는 틸 베이스. 유동적이고 역동적인 이 디자인은 바다 물결의 움직임을 메탈릭한 형태로 포착합니다.',
        'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.': '피치와 마젠타 색상의 부드럽고 확산된 아우라 그라데이션. 신체의 미묘한 에너지 장을 모방한 깊이 있고 영적인 글로잉 디자인입니다.',
        'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.': '골드 스터드 지오메트릭 패턴이 있는 블랙 매트. 강력하고 자신감 넘치며 당당하게 대담합니다. 분위기를 압до하는 분들을 위한 디자인입니다.',
        // Services - Names
        'Classic Manicure': '클래식 매니큐어',
        'Regular Polish': '일반 폴리시',
        'Gel Polish': '젤 폴리시',
        'Cat Eye': '캣아이',
        'Full French Tip': '풀 프렌치 팁',
        'Full Ombre': '풀 옴브레',
        'Full Chrome': '풀 크롬',
        'Full Cat Eye': '풀 캣아이',
        'Bespoke Artistry': '커스텀 아트',
        'Classic Shampoo': '클래식 샴푸',
        'Deluxe Shampoo': '디럭스 샴푸',
        'Luxury Shampoo': '럭셔리 샴푸',
        // Services - Descriptions
        'Essential nail care, cuticle work, and shaping.': '기본 네일 케어, 큐티클 정리 및 모양 잡기.',
        'Standard nail polish application.': '일반 네일 폴리시 도포.',
        'Long-lasting gel polish.': '오래 지속되는 젤 폴리시.',
        'Magnetic cat eye gel effect.': '마그네틱 캣아이 젤 효과.',
        'Classic or modern French tips on all nails.': '모든 손톱에 클래식 또는 모던 프렌치 팁.',
        'Smooth gradient color transition.': '부드러운 그라데이션 컬러 전환.',
        'Metallic chrome finish.': '메탈릭 크롬 마무리.',
        'Intense magnetic cat eye on all nails.': '모든 손톱에 강렬한 마그네틱 캣아이.',
        'Custom, hand-painted sets tailored to your vision.': '당신의 비전에 맞춘 커스텀 핸드 페인팅 세트.',
        'Standard relaxing hair wash.': '기본 릴랙싱 헤어 샴푸.',
        'Deep scalp massage and hair nourishment.': '심층 두피 마사지 및 모발 영양 공급.',
        'Ultimate relaxation with neck and shoulder massage.': '목과 어깨 마사지를 포함한 궁극의 휴식.',

        // Hero
        'h-title-art': 'The |Art| of',
        'h-title-precision': 'Precision.',
        'h-btn-explore': '아틀리에 탐험하기',
        'h-btn-about': '회사 소개',
        'h-label-atelier': '디지털 아틀리에',
        'ed-discover': '완벽함을 발견하세요',
        'ed-craft': '당신의 정체성을 만드세요',
        'ed-book': '지금 예약하기',
        'ed-related': '관련 통찰력',

        // CTA
        'cta-title': '예약하기.',
        'cta-desc': '이번 시즌 시내 스튜디오의 예약이 한정되어 있습니다.',
        'cta-btn': '지금 예약',

        // Visual Break
        'vb-glass-title': '글래스 네일',
        'vb-glass-sub': '유리 효과',
        'vb-chrome-title': '크롬 아트',
        'vb-chrome-sub': '메탈릭 실버',
        'vb-3d-title': '3D · 샴페인',
        'vb-3d-sub': '샴페인 골드',

        // Brief Intro
        'intro-text': 'REMY MUSE는 현대적인 네일 아틀리에입니다. 모든 디테일은 섬세하게 완성됩니다. 당신을 위해 디자인됩니다.',

        // Testimonials
        'review-role': '고객',
        'review-1-quote': '"매우 꼼꼼하고 깨끗한 작업입니다. 새 네일이 아주 마음에 들어요."',
        'review-2-quote': '"직원들이 친절하고 상냥합니다. 분위기가 정말 편안해요."',
        'review-3-quote': '"세심한 서비스와 열정적인 상담. 꼭 다시 방문하겠습니다."',

        // Catalog
        'catalog-btn': '전체 서비스 카탈로그 보기 →',
        'catalog-close': '닫기',

        'nav-booking': '예약하기',
        's-menu-label': '서비스',
        'vc-trending': '트렌딩',
        'vc-gallery-label': '포트폴리오',
        'vc-gallery-title': '디자인 포트폴리오',
        'vc-gallery-subtitle': '일상과 특별한 순간을 위한 심플하고 깔끔한 디자인.',
        'vc-no-match': '선택하신 조건에 맞는 디자인이 없습니다.',
        'vc-latest-featured': '최신 주요 작품',
        'vc-view-full': '전체 갤러리 보기',
        'fa-call': '전화하기',
        'fa-book': '예약하기',
        'bp-label': '인사이트',
        'bp-title': '인사이트',
        'bp-desc': '네일을 위한 간단한 팁, 트렌드 및 아이디어.',
        'bp-trending': '추천 게시물',
        'bp-view-all': '전체 라이브러리 탐색',

        // Booking
        'ft-studio-desc': 'Nail — Shampoo — Foot Care Studio',
        'booking-err-fail': '예약 생성에 실패했습니다',
    },
    CN: {
        'h-eyebrow': '奢华美甲工作室 · 岘港',
        'h-sub': '服务菜单',
        's-muse-title': '美甲与足部护理',
        's-muse-sub': '基础指甲护理',
        'h-quote': '艺境源于<span>关怀</span>。我们不仅在设计美甲，更在聆听并珍视您的故事。',
        'h-scroll': '向下滚动',
        's1-title': '美甲服务', 's1-sub': '指甲护理',
        's2-title': '足部护理', 's2-sub': '脚部护理',
        's3-title': '附加服务', 's3-sub': '可选附加',
        's4-title': '头发与头皮', 's4-sub': '草本洗发',
        'g-manicure': '美甲', 'g-enhance': '延甲', 'g-art': '美甲艺术',
        'art-note': '美甲艺术价格不含凝胶指甲油',
        'n-classic-vi': '经典美甲', 'd-classic': '修剪定型、护理甲皮、热毛巾、护手霜。',
        'n-deluxemani-vi': '豪华美甲', 'd-deluxemani': '修剪定型、护理甲皮、冷却凝胶面膜、护手霜手部按摩。',
        'n-regpol-vi': '普通指甲油', 'n-gelpol-vi': '凝胶指甲油',
        'n-gelx-vi': 'Gel-X全套', 'n-buildergel-vi': '构建凝胶全套',
        'n-acrylic-vi': '丙烯酸全套', 'n-refill-vi': '丙烯酸/构建凝胶补充',
        'n-dual-vi': '双模具全套', 'n-biab-vi': 'BIAB覆盖',
        'n-french-vi': '法式美甲', 'n-ombre-vi': '渐变色', 'n-chrome-vi': '镭射粉',
        'n-cateye-vi': '猫眼', 'n-minimal-vi': '简约美甲',
        'n-3d-vi': '3D艺术/水钻/吊坠', 'n-custom-vi': '手绘定制设计',
        's-essential-title': '基础美甲艺术', 's-essential-sub': '核心设计',
        'n-essential-items': '全手法式 / 渐变 / 魔镜粉 / 猫眼',
        'n-full-french': '全手法式 (Full French Tip)', 'n-full-ombre': '全手渐变 (Full Ombre)',
        'n-full-chrome': '全手魔镜粉 (Full Chrome)', 'n-full-cateye': '全手猫眼 (Full Cat Eye)',
        's-bespoke-title': '定制美甲艺术', 's-bespoke-sub': '定制艺术',
        's-ritual-title': '洗发与放松', 's-ritual-sub': '修复水疗',
        'n-bespoke-items': '根据您的构思量身定制的手绘款式', 'p-on-request': '价格面议',
        'pu1': '/ 指', 'pu2': '/ 指', 'pu3': '/ 指',
        'n-classpedi-vi': '经典足部护理', 'd-classpedi': '草本泡脚、去除老茧、去角质、修剪指甲、护理甲皮、热毛巾、涂霜。',
        'n-deluxepedi-vi': '豪华足部护理', 'd-deluxepedi': '4步豪华套装：护甲皮、修剪、面膜、足部按摩。',
        'n-gelcolor-vi': '凝胶颜色', 'n-regcolor-vi': '普通颜色',
        'n-remacrylic-vi': '卸除丙烯酸/Gel-X', 'n-remgel-vi': '卸除凝胶',
        'n-classic30-vi': '经典洗发', 'd-classic30': '干式头皮按摩，草本油洗发两次，草本护发素按摩，基础颈肩按摩。',
        'n-deluxe70-vi': '豪华洗发', 'n-luxury90-vi': '奢华洗发',
        'sum-d70-txt': '查看16步流程', 'sum-l90-txt': '查看19步流程',
        'ft-tagline': 'Nail Studio · 岘港',
        'ft-note': '价格不含税<br>如有变动恕不另行通知<br>© REMY MUSE Nail Studio',

        // Footer & Map Section
        'nav-portfolio': '作品集',
        'nav-services': '服务',
        'nav-editorial': '社论',
        'nav-location': '位置',
        'nav-privacy': '隐私',
        'ft-rights': '保留所有权利',

        'map-visit': '访问我们',
        'map-desc': '位于岘港安海的现代美甲工作室。',
        'map-hours': '营业时间',
        'map-days': '周一 - 周日',
        'map-hotline': '热线电话',
        'map-directions': '获取路线',
        'map-hub': '美学中心',
        'map-address': '岘港安海 21 An Nhon 6 (Phan Boi x An Nhon 6 十字路口)',
        'map-connect': '联系我们',
        'map-open-maps': '在地图中打开',
        // Booking & Gallery Base EN
        'The Muse Gallery': '缪斯艺术廊',
        'A curated exhibition of our finest artistry. From timeless French tips to avant-garde 3D floral expressions.': '这是一个精选空间，我们在这里挑选最美丽和满意的指甲设计——从简单、熟悉的法式指甲到创意的3D花卉设计。',
        'Experience': '体验',
        'Schedule': '预约',
        'Contact': '联系',
        'Reserve': '预订',
        'Your Session': '您的预约',
        'A curated encounter with stillness. No deposit required at this stage.': '精心安排的宁静邂逅。此阶段无需押金。',
        'Phase 0': '阶段 0',
        'Instant Notification': '即时通知',
        'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.': '选择后，工作室团队将立即收到通知。如有特殊要求，请通过下方电话或聊天与我们联系。',
        'Select': '选择',
        'Artistry': '艺术性',
        'Choose your signature experience.': '选择您的专属体验。',
        'Preparing the catalog...': '正在准备目录...',
        'The': '',
        'Timeline': '时间线',
        'Reserve your preferred arrival window.': '预订您喜欢的到达时间段。',
        'Select Time Window': '选择时间段',
        'You have selected': '您已选择',
        'at': ' 时间：',
        'Personal': '个人信息',
        'Identifier': '身份标识',
        'Finalize your reservation details.': '完善您的预约详情。',
        'Your Name': '您的姓名',
        'Enter full name': '输入全名',
        'Phone Number': '电话号码',
        'Finalizing Reservation...': '正在完成预约...',
        'Confirm Atelier Reservation': '确认工作室预约',
        'Previous Phase': '上一步',
        'Next Phase': '下一步',
        'Success.': '成功。',
        'Your request for': '您所选的 ',
        'on': ' 预约日期：',
        'has been recorded.': ' 预约请求已成功提交。',
        'Finalize Experience': '完成预约',
        // Services - Names
        'Classic Manicure': '经典美甲',
        'Regular Polish': '普通指甲油',
        'Gel Polish': '凝胶指甲油',
        'Cat Eye': '猫眼美甲',
        'Full French Tip': '全手法式',
        'Full Ombre': '全手渐变',
        'Full Chrome': '全手魔镜粉',
        'Full Cat Eye': '全手猫眼',
        'Bespoke Artistry': '定制艺术',
        'Classic Shampoo': '经典洗发',
        'Deluxe Shampoo': '豪华洗发',
        'Luxury Shampoo': '奢华洗发',
        // Services - Descriptions
        'Essential nail care, cuticle work, and shaping.': '基础指甲护理、去死皮及修甲型。',
        'Standard nail polish application.': '标准指甲油涂抹。',
        'Long-lasting gel polish.': '持久凝胶指甲油。',
        'Magnetic cat eye gel effect.': '磁性猫眼凝胶效果。',
        'Classic or modern French tips on all nails.': '全手经典或现代法式指甲。',
        'Smooth gradient color transition.': '平滑的渐变颜色过渡。',
        'Metallic chrome finish.': '金属质感魔镜粉效果。',
        'Intense magnetic cat eye on all nails.': '全手强效磁性猫眼效果。',
        'Custom, hand-painted sets tailored to your vision.': '根据您的构思量身定制的手绘款式。',
        'Standard relaxing hair wash.': '标准放松洗发服务。',
        'Deep scalp massage and hair nourishment.': '深层头皮按摩及头发滋养。',
        'Ultimate relaxation with neck and shoulder massage.': '包含颈肩按摩的极致放松体验。',
        'Other': '其他',
        'Nail Services': '美甲服务',
        'Pedicure': '足部护理',
        'Add-On': '附加服务',
        'Hair & Scalp': '头发与头皮',
        'Days-Su': '日',
        'Days-Mo': '一',
        'Days-Tu': '二',
        'Days-We': '三',
        'Days-Th': '四',
        'Days-Fr': '五',
        'Days-Sa': '六',
        'Infinite Design Matrix': '无限设计矩阵',
        'Scroll to Navigate': '滚动导航',
        'Click to Explore': '点击探索',
        'Swipe · Tap to Explore': '滑动 · 点击探索',
        'Design Detail': '设计详情',
        'File': '档案',
        'Collection': '系列',
        'Close': '关闭',
        'Glass Nails': '琉璃美甲',
        'Chrome Luxe': '奢华魔镜',
        'Gold Foil': '金箔艺术',
        'Vamp Romantic': '吸血鬼浪漫',
        'Bridal': '新娘系列',
        'Ombre': '渐变艺术',
        'Minimalist': '极简主义',
        'Marble Luxe': '大理石纹',
        'Botanical': '植物系列',
        'Chrome': '魔镜粉',
        'Animal Print': '动物纹',
        'Constellation': '星空系列',
        'Pearl': '珍珠系列',
        'Holographic': '激光幻彩',
        'Classic': '经典款',
        'Line Art': '线条艺术',
        'Coral': '珊瑚色',
        'Geometric': '几何图形',
        'Crystal': '水晶装饰',
        'Chain': '金属链条',
        'Metallic': '金属质感',
        'Abstract': '抽象艺术',
        'Aura': '光晕系列',
        'Dark Luxe': '深色奢华',
        'Ethereal — No. 01': '灵动 — No. 01',
        'Gilded — No. 02': '镀金 — No. 02',
        'Dust & Gold — No. 03': '尘金 — No. 03',
        'Merlot — No. 04': '美乐 — No. 04',
        'Petals — No. 05': '花瓣 — No. 05',
        'Rosé — No. 06': '罗塞 — No. 06',
        'Ink — No. 07': '水墨 — No. 07',
        'Verde — No. 08': '翠绿 — No. 08',
        'Fluidity — No. 09': '流体 — No. 09',
        'Sakura — No. 10': '樱花 — No. 10',
        'Rose Gold — No. 11': '玫瑰金 — No. 11',
        'Tortoise — No. 12': '玳瑁 — No. 12',
        'Midnight — No. 13': '午夜 — No. 13',
        'Velvet Pearl — No. 14': '天鹅绒珍珠 — No. 14',
        'Prism — No. 15': '棱镜 — No. 15',
        'Rouge — No. 16': '胭脂 — No. 16',
        'Gilded Veins — No. 17': '金纹 — No. 17',
        'Sunset — No. 18': '日落 — No. 18',
        'Slate — No. 19': '石板 — No. 19',
        'Champagne — No. 20': '香槟 — No. 20',
        'Link — No. 21': '链接 — No. 21',
        'Tidal — No. 22': '潮汐 — No. 22',
        'Blush Aura — No. 23': '红晕光晕 — No. 23',
        'Obsidian — No. 24': '黑曜石 — No. 24',
        'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.': '带有液体魔镜波纹的半透明果冻甲。REMY MUSE 的招牌设计，捕捉光影与律动，打造出随姿势变换而流转的空灵玻璃质感。',
        'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.': '带有法式轮廓的纯 24K 金魔镜。大胆而精致，镜面般的效果尽显奢华，在任何场合都夺人眼球。',
        'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.': '带有手工贴金箔碎片的裸色磨砂底色。每一片指甲都成为有机奢华的画布，独一无二。',
        'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.': '带有金色旋涡装饰和层叠珠宝的深酒红色。这种充满戏剧性和浪漫色彩的设计从复古美学中汲取灵感，并融合了现代社论风格。',
        'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.': '带有雕刻 3D 花卉装饰的珍珠魔镜。我们最受欢迎的新娘设计，以手工制作的瓷花和微型水晶中心为特色。',
        'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.': '带有散落金箔的柔和粉白渐变。精致且充满女性气质的设计，可完美胜任从白天到晚间的各种场合。',
        'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.': '在纯净白色画布上的大胆黑色几何线条艺术。灵感源自现代主义绘画，这种极简主义设计通过精准而自信的笔触表达自我。',
        'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.': '带有手绘金色金缮纹理的祖母绿。受日本金缮艺术（用金修复破碎陶器）的启发，赞美不完美之美。',
        'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.': '带有流动银色魔镜滴痕的透明负空间。一种前卫的美甲艺术，挑战液体与固体形式的边界。',
        'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.': '带有手绘樱花枝的奶白色美甲。每一片花瓣都由我们的高级技师单独绘制，是真正的定制植物艺术品。',
        'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.': '带有精致叠戴戒指效果的温暖玫瑰金镜面。极致的低调奢华，这种金属质感能衬托各种肤色。',
        'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.': '带有金色微粒的琥珀玳瑁图案。对动物纹的精致演绎，让人联想起复古奢侈配件。',
        'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.': '带有手绘金色星座图案的海军蓝。一种天体设计，以天文般的精确度将星空绘于指尖。',
        'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.': '带有精致珍珠装饰的粉色天鹅绒磨砂。柔软、触感细腻，散发出无法抗拒的女性魅力——如同在指甲上穿着丝绸。',
        'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.': '捕捉彩虹每种颜色的全光谱激光幻彩。为内心强大而大胆的人设计的未来感十足、引人注目的设计。',
        'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.': '带有金色半月甲皮细节的永恒深红。对经典好莱坞魅力美甲的现代重新诠释。',
        'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.': '带有精细金色线条艺术（细致的旋涡和微点）的裸粉色底色。灵感源自天然矿物纹理，设计微妙且复杂。',
        'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.': '带有金箔亮片的温暖珊瑚色。如阳光亲吻般的设计，带来温暖与活力，是夏日夜晚的完美选择。',
        'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.': '带有银色魔镜几何图案的磨砂石板灰。锐利的建筑线条与柔和的灰色调相遇，营造出当代城市美学。',
        'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.': '点缀施华洛世奇水晶的金色亮片。极致的庆典美甲——专为那些最耀眼的时刻而设计。',
        'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.': '带有 3D 金色链条装饰的灰紫色。一个大胆、前卫的时尚宣言，架起了珠宝与美甲艺术之间的桥梁。',
        'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.': '带有银色魔镜波浪图案的蓝绿色底色。流体且充满动感，这种设计以金属形式捕捉了海浪的运动。',
        'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.': '桃红色和洋红色的柔和扩散光晕渐变。一种深具精神色彩、发光的设计，模拟人体空灵的能量场。',
        'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.': '带有金色铆钉几何图案的黑色磨砂。强大、自信且毫不掩饰的大胆——献给那些掌控全局的人。',
        'h-title-art': 'The |Art| of',
        'h-title-precision': 'Precision.',
        'h-btn-explore': '探索工作室',
        'h-btn-about': '关于我们',
        'h-label-atelier': '数字工作室',
        'ed-discover': '探索完美',
        'ed-craft': '塑造您的身份',
        'ed-book': '立即预约',
        'ed-related': '相关洞察',
        'cta-title': '立即预约。',
        'cta-desc': '本季度我们市中心工作室的预约名额有限。',
        'cta-btn': '预约服务',
        'vb-glass-title': '琉璃美甲',
        'vb-glass-sub': '玻璃效果',
        'vb-chrome-title': '魔镜艺术',
        'vb-chrome-sub': '金属银',
        'vb-3d-title': '3D · 香槟',
        'vb-3d-sub': '香槟金',
        'intro-text': 'REMY MUSE 是一家现代美甲沙龙。匠心雕琢每一处细节，只为你而设计。',
        'review-role': '客户',
        'review-1-quote': '"工作非常细致干净。我对我的新指甲非常满意。"',
        'review-2-quote': '"员工温柔和善。氛围非常放松。"',
        'review-3-quote': '"服务周到，咨询热情。我一定会再来的。"',
        'catalog-btn': '查看完整菜单 →',
        'catalog-close': '关闭',

        'nav-booking': '立即预约',
        's-menu-label': '服务项目',
        'vc-trending': '趋势',
        'vc-gallery-label': '作品集',
        'vc-gallery-title': '设计作品集',
        'vc-gallery-subtitle': '适合日常和特别场合的简约纯净设计。',
        'vc-no-match': '没有符合您选择的设计。',
        'vc-latest-featured': '最新精选作品',
        'vc-view-full': '查看完整画廊',
        'fa-call': '立即致电',
        'fa-book': '立即预约',
        'bp-label': '深度洞察',
        'bp-title': '深度洞察',
        'bp-desc': '简单的美甲技巧、趋势和创意。',
        'bp-trending': '编辑精选',
        'bp-view-all': '浏览完整库',

        'ft-studio-desc': 'Nail — Shampoo — Foot Care Studio',
        'booking-err-fail': '创建预约失败',
    },
    RU: {
        'h-eyebrow': 'Люкс Нейл Студио · Да-Нанг',
        'h-sub': 'Меню услуг',
        's-menu-label': 'Услуги',
        's-muse-title': 'Маникюр и Педикюр',
        's-muse-sub': 'Базовый уход за ногтями',
        'h-quote': 'Искусство, рожденное из <span>заботы</span>. Мы не просто создаем дизайн ногтей — мы дорожим вашей историей.',
        'h-scroll': 'Вниз',
        's1-title': 'Ногтевой сервис', 's1-sub': 'Уход за ногтями',
        's2-title': 'Педикюр', 's2-sub': 'Уход за ногами',
        's3-title': 'Дополнительные', 's3-sub': 'Дополнения',
        's4-title': 'Волосы и кожа', 's4-sub': 'Травяной шампунь',
        'g-manicure': 'Маникюр', 'g-enhance': 'Наращивание ногтей', 'g-art': 'Дизайн ногтей',
        'art-note': 'Цены на дизайн не включают гель-лак',
        'n-classic-vi': 'Классический маникюр', 'd-classic': 'Обрезка и форма, уход за кутикулой, горячее полотенце, крем для рук.',
        'n-deluxemani-vi': 'Делюкс маникюр', 'd-deluxemani': 'Обрезка, уход за кутикулой, охлаждающая гель-маска, массаж рук с кремом.',
        'n-regpol-vi': 'Обычный лак', 'n-gelpol-vi': 'Гель-лак',
        'n-gelx-vi': 'Гель-Х полный набор', 'n-buildergel-vi': 'Билдер-гель полный набор',
        'n-acrylic-vi': 'Акрил полный набор', 'n-refill-vi': 'Акрил/билдер-гель рефил',
        'n-dual-vi': 'Дуал форм полный набор', 'n-biab-vi': 'BIAB оверлей',
        'n-french-vi': 'Французский маникюр', 'n-ombre-vi': 'Омбре', 'n-chrome-vi': 'Хромовый порошок',
        'n-cateye-vi': 'Кошачий глаз', 'n-minimal-vi': 'Минималистичный дизайн',
        'n-3d-vi': '3D-арт/стразы/шармы', 'n-custom-vi': 'Роспись ногтей на заказ',
        's-essential-title': 'Базовый дизайн', 's-essential-sub': 'Основное искусство',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Френч (все ногти)', 'n-full-ombre': 'Омбре (все ногти)',
        'n-full-chrome': 'Втирка (все ногти)', 'n-full-cateye': 'Кошачий глаз (все ногти)',
        's-bespoke-title': 'Индивидуальный дизайн', 's-bespoke-sub': 'Уникальный стиль',
        's-ritual-title': 'Шампунь и расслабление', 's-ritual-sub': 'Восстанавливающий спа',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': 'Цена по запросу',
        'pu1': '/ ноготь', 'pu2': '/ ноготь', 'pu3': '/ ноготь',
        'n-classpedi-vi': 'Классический педикюр', 'd-classpedi': 'Травяная ванночка, пилинг, скраб, обрезка, уход за кутикулой, горячее полотенце, крем.',
        'n-deluxepedi-vi': 'Делюкс педикюр', 'd-deluxepedi': '4-шаговый набор Deluxe: уход за кутикулой, обрезка, маска, массаж ног.',
        'n-gelcolor-vi': 'Гель-цвет', 'n-regcolor-vi': 'Обычный цвет',
        'n-remacrylic-vi': 'Снятие акрила/Гель-Х', 'n-remgel-vi': 'Снятие гель-лака',
        'n-classic30-vi': 'Классический шампунь', 'd-classic30': 'Сухой массаж кожи головы, двойное мытьё с травяным маслом, массаж с кондиционером, массаж шеи и плеч.',
        'n-deluxe70-vi': 'Делюкс шампунь', 'n-luxury90-vi': 'Люкс шампунь',
        'sum-d70-txt': 'Посмотреть 16 шагов', 'sum-l90-txt': 'Посмотреть 19 шагов',
        'ft-tagline': 'Nail Studio · Да-Нанг',
        'ft-note': 'Цены без учёта налогов<br>Возможны изменения без предупреждения<br>© REMY MUSE Nail Studio',

        // Footer & Map Section
        'nav-portfolio': 'Портфолио',
        'nav-services': 'Услуги',
        'nav-editorial': 'Редакция',
        'nav-location': 'Локация',
        'nav-privacy': 'Конфиденциальность',
        'ft-rights': 'Все права защищены',

        'map-visit': 'Посетите нас',
        'map-desc': 'Современная студия маникюра в Ан Хай, Дананг.',
        'map-hours': 'Часы работы',
        'map-days': 'Пн - Вс',
        'map-hotline': 'Прямая линия',
        'map-directions': 'Маршрут',
        'map-hub': 'Эстетический центр',
        'map-address': '21 An Nhon 6, Ан Хай, Дананг (перекресток Phan Boi x An Nhon 6)',
        'map-connect': 'Свяжитесь с нами',
        'map-open-maps': 'Открыть в картах',
        // Booking & Gallery Base EN
        'The Muse Gallery': 'Галерея Муза',
        'A curated exhibition of our finest artistry. From timeless French tips to avant-garde 3D floral expressions.': 'Курируемое пространство, где мы отбираем самые красивые и удачные дизайны ногтей — от простых, знакомых французских кончиков до креативных 3D-цветочных дизайнов.',
        'Experience': 'Опыт',
        'Schedule': 'График',
        'Contact': 'Контакт',
        'Reserve': 'Забронировать',
        'Your Session': 'Ваш сеанс',
        'A curated encounter with stillness. No deposit required at this stage.': 'Кураторская встреча с тишиной. На данном этапе депозит не требуется.',
        'Phase 0': 'Этап 0',
        'Instant Notification': 'Мгновенное уведомление',
        'The atelier team is notified instantly upon your selection. For specific requests, please contact us via phone or chat in the section below.': 'Команда ателье мгновенно получает уведомление о вашем выборе. По особым запросам, пожалуйста, свяжитесь с нами по телефону или в чате ниже.',
        'Select': 'Выбрать',
        'Artistry': 'Мастерство',
        'Choose your signature experience.': 'Выберите свой фирменный опыт.',
        'Preparing the catalog...': 'Подготовка каталога...',
        'The': '',
        'Timeline': 'Хронология',
        'Reserve your preferred arrival window.': 'Забронируйте удобное время прибытия.',
        'Select Time Window': 'Выберите временное окно',
        'You have selected': 'Вы выбрали',
        'at': 'в',
        'Personal': 'Личные данные',
        'Identifier': 'Идентификатор',
        'Finalize your reservation details.': 'Завершите оформление бронирования.',
        'Your Name': 'Ваше имя',
        'Enter full name': 'Введите полное имя',
        'Phone Number': 'Номер телефона',
        'Finalizing Reservation...': 'Завершение бронирования...',
        'Confirm Atelier Reservation': 'Подтвердить бронирование в ателье',
        'Previous Phase': 'Предыдущий этап',
        'Next Phase': 'Следующий этап',
        'Success.': 'Успех.',
        'Your request for': 'Ваш запрос на',
        'on': 'на',
        'has been recorded.': 'был записан.',
        'Finalize Experience': 'Завершить опыт',
        // Services - Names
        'Classic Manicure': 'Классический маникюр',
        'Regular Polish': 'Обычный лак',
        'Gel Polish': 'Гель-лак',
        'Cat Eye': 'Кошачий глаз',
        'Full French Tip': 'Френч на все ногти',
        'Full Ombre': 'Омбре на все ногти',
        'Full Chrome': 'Втирка на все ногти',
        'Full Cat Eye': 'Кошачий глаз на все ногти',
        'Bespoke Artistry': 'Индивидуальный дизайн',
        'Classic Shampoo': 'Классический шампунь',
        'Deluxe Shampoo': 'Делюкс шампунь',
        'Luxury Shampoo': 'Люкс шампунь',
        // Services - Descriptions
        'Essential nail care, cuticle work, and shaping.': 'Базовый уход за ногтями, обработка кутикулы и придание формы.',
        'Standard nail polish application.': 'Стандартное нанесение лака для ногтей.',
        'Long-lasting gel polish.': 'Долговечное покрытие гель-лаком.',
        'Magnetic cat eye gel effect.': 'Гель-лак с эффектом «кошачий глаз».',
        'Classic or modern French tips on all nails.': 'Классический или современный френч на всех ногтях.',
        'Smooth gradient color transition.': 'Плавный градиентный переход цвета.',
        'Metallic chrome finish.': 'Металлическое зеркальное покрытие.',
        'Intense magnetic cat eye on all nails.': 'Интенсивный эффект кошачьего глаза на всех ногтях.',
        'Custom, hand-painted sets tailored to your vision.': 'Индивидуальные наборы с ручной росписью по вашему эскизу.',
        'Standard relaxing hair wash.': 'Стандартное расслабляющее мытье головы.',
        'Deep scalp massage and hair nourishment.': 'Глубокий массаж кожи головы и питание волос.',
        'Ultimate relaxation with neck and shoulder massage.': 'Максимальное расслабление с массажем шеи и плеч.',
        'Other': 'Другое',
        'Nail Services': 'Услуги маникюра',
        'Pedicure': 'Педикюр',
        'Add-On': 'Доп. услуга',
        'Hair & Scalp': 'Волосы и кожа головы',
        'Days-Su': 'Вс',
        'Days-Mo': 'Пн',
        'Days-Tu': 'Вт',
        'Days-We': 'Ср',
        'Days-Th': 'Чт',
        'Days-Fr': 'Пт',
        'Days-Sa': 'Сб',
        'Infinite Design Matrix': 'Матрица бесконечного дизайна',
        'Scroll to Navigate': 'Прокрутите для навигации',
        'Click to Explore': 'Нажмите для изучения',
        'Swipe · Tap to Explore': 'Проведите · Нажмите для изучения',
        'Design Detail': 'Детали дизайна',
        'File': 'Файл',
        'Collection': 'Коллекция',
        'Close': 'Закрыть',
        'Glass Nails': 'Стеклянные ногти',
        'Chrome Luxe': 'Хром Люкс',
        'Gold Foil': 'Золотая фольга',
        'Vamp Romantic': 'Вампирская романтика',
        'Bridal': 'Свадебный',
        'Ombre': 'Омбре',
        'Minimalist': 'Минимализм',
        'Marble Luxe': 'Мрамор Люкс',
        'Botanical': 'Ботаника',
        'Chrome': 'Хром',
        'Animal Print': 'Анималистичный принт',
        'Constellation': 'Созвездие',
        'Pearl': 'Жемчуг',
        'Holographic': 'Голография',
        'Classic': 'Классика',
        'Line Art': 'Линейный арт',
        'Coral': 'Коралл',
        'Geometric': 'Геометрия',
        'Crystal': 'Кристалл',
        'Chain': 'Цепь',
        'Metallic': 'Металлик',
        'Abstract': 'Абстракция',
        'Aura': 'Аура',
        'Dark Luxe': 'Темный Люкс',
        'Ethereal — No. 01': 'Эфирный — №01',
        'Gilded — No. 02': 'Позолоченный — №02',
        'Dust & Gold — No. 03': 'Пыль и золото — №03',
        'Merlot — No. 04': 'Мерло — №04',
        'Petals — No. 05': 'Лепестки — №05',
        'Rosé — No. 06': 'Розе — №06',
        'Ink — No. 07': 'Чернила — №07',
        'Verde — No. 08': 'Верде — №08',
        'Fluidity — No. 09': 'Текучесть — №09',
        'Sakura — No. 10': 'Сакура — №10',
        'Rose Gold — No. 11': 'Розовое золото — №11',
        'Tortoise — No. 12': 'Черепаха — №12',
        'Midnight — No. 13': 'Полночь — №13',
        'Velvet Pearl — No. 14': 'Бархатный жемчуг — №14',
        'Prism — No. 15': 'Призма — №15',
        'Rouge — No. 16': 'Руж — №16',
        'Gilded Veins — No. 17': 'Золотые вены — №17',
        'Sunset — No. 18': 'Закат — №18',
        'Slate — No. 19': 'Сланцевый — №19',
        'Champagne — No. 20': 'Шампань — №20',
        'Link — No. 21': 'Связь — №21',
        'Tidal — No. 22': 'Прилив — №22',
        'Blush Aura — No. 23': 'Румяная аура — №23',
        'Obsidian — No. 24': 'Обсидиан — №24',
        'Translucent jelly nails with liquid chrome waves. A signature REMY MUSE design that captures light and movement, creating an ethereal, glass-like finish that shifts with every gesture.': 'Полупрозрачные желейные ногти с волнами жидкого хрома. Фирменный дизайн REMY MUSE, который улавливает свет и движение, создавая воздушный, похожий на стекло финиш, меняющийся при каждом жесте.',
        'Pure 24K gold chrome with a French silhouette. Bold yet refined, this design embodies opulence with a mirror-like finish that demands attention in any setting.': 'Чистый 24-каратный золотой хром с французским силуэтом. Смелый, но изысканный дизайн, воплощающий роскошь с зеркальным блеском, который привлекает внимание в любой обстановке.',
        'Nude matte base with hand-applied gold leaf fragments. Each nail becomes a canvas of organic luxury, where no two designs are exactly alike.': 'Матовая нюдовая база с нанесенными вручную фрагментами сусального золота. Каждый ноготь становится холстом органической роскоши, где ни один дизайн не повторяется.',
        'Deep burgundy with gold swirl accents and layered jewelry. This dramatic, romantic design draws from vintage aesthetics with a modern, editorial edge.': 'Глубокий бордовый с золотыми вихревыми акцентами и многослойными украшениями. Этот драматичный романтичный дизайн черпает вдохновение в винтажной эстетике с современным редакционным оттенком.',
        'Pearl chrome with sculpted 3D floral embellishments. Our most requested bridal design, featuring hand-crafted porcelain flowers and micro-crystal centers.': 'Жемчужный хром с лепными 3D цветочными украшениями. Наш самый востребованный свадебный дизайн с фарфоровыми цветами ручной работы и центрами из микрокристаллов.',
        'Soft pink-to-white gradient with scattered gold leaf. A delicate, feminine design that transitions seamlessly from day to evening occasions.': 'Нежный градиент от розового к белому с вкраплениями сусального золота. Изящный женственный дизайн, идеально подходящий как для дневных, так и для вечерних мероприятий.',
        'Bold black geometric line art on a crisp white canvas. Inspired by modernist painting, this minimalist design speaks through its precise, confident strokes.': 'Смелый черный геометрический линейный арт на чистом белом холсте. Вдохновленный модернистской живописью, этот минималистичный дизайн говорит через точные и уверенные штрихи.',
        'Emerald green with hand-painted gold kintsugi veins. A celebration of imperfection and beauty, inspired by the Japanese art of repairing broken pottery with gold.': 'Изумрудно-зеленый с нарисованными вручную золотыми венами в стиле кинцуги. Торжество несовершенства и красоты, вдохновленное японским искусством ремонта разбитой керамики золотом.',
        'Clear negative space with fluid silver chrome drips. An avant-garde approach to nail art that plays with the boundaries of liquid and solid forms.': 'Прозрачное негативное пространство с текучими каплями серебристого хрома. Авангардный подход к нейл-арту, играющий с границами жидких и твердых форм.',
        'Milky white nails with hand-painted cherry blossom branches. Each petal is individually rendered by our master artists for a truly bespoke botanical piece.': 'Молочно-белые ногти с нарисованными вручную ветвями вишни. Каждый лепесток индивидуально прорисован нашими мастерами для создания по-настоящему уникальной ботанической композиции.',
        'Warm rose gold mirror chrome with delicate stacking rings. The ultimate in understated luxury, this metallic finish flatters every skin tone.': 'Теплый зеркальный хром цвета розового золота с изящными имитациями наборных колец. Вершина сдержанной роскоши, этот металлический финиш подчеркивает любой оттенок кожи.',
        'Amber tortoiseshell pattern with gold micro-flecks. A sophisticated take on animal print that evokes vintage luxury accessories.': 'Янтарный черепаховый узор с золотыми микро-вкраплениями. Изысканная интерпретация анималистичного принта, напоминающая винтажные роскошные аксессуары.',
        'Navy blue with hand-painted gold constellation patterns. A celestial design that maps the stars onto your fingertips with astronomical precision.': 'Темно-синий с нарисованными вручную золотыми узорами созвездий. Небесный дизайн, переносящий карту звезд на ваши кончики пальцев с астрономической точностью.',
        'Blush pink velvet matte with delicate pearl embellishments. Soft, tactile, and irresistibly feminine — like wearing silk on your nails.': 'Розовый бархатный матовый финиш с нежными жемчужными украшениями. Мягкий, тактильный и непреодомимо женственный — словно шелк на ваших ногтях.',
        'Full-spectrum holographic chrome that captures every color of the rainbow. A futuristic, show-stopping design for the bold at heart.': 'Полноспектральный голографический хром, улавливающий все цвета радуги. Футуристичный, потрясающий дизайн для смелых сердцем.',
        'Timeless crimson red with gold half-moon cuticle detail. A modern reinterpretation of the classic Hollywood glamour manicure.': 'Вневременной малиново-красный с золотой деталью "полумесяца" у кутикулы. Современная реинтерпретация классического голливудского гламурного маникюра.',
        'Nude pink base with fine gold line art — delicate swirls and micro-dots. Inspired by natural mineral veins, this design is subtle yet intricate.': 'Нюдово-розовая база с тонким золотым линейным артом — изящными завитками и микро-точками. Вдохновленный природными минеральными жилами, этот дизайн тонок, но сложен.',
        'Warm coral with gold foil flake accents. A sun-kissed design that brings warmth and vitality, perfect for summer evenings.': 'Теплый коралл с акцентами в виде хлопьев золотой фольги. "Поцелованный солнцем" дизайн, приносящий тепло и жизненную силу, идеально подходит для летних вечеров.',
        'Matte slate grey with silver chrome geometric patterns. Sharp, architectural lines meet soft grey tones for a contemporary, urban aesthetic.': 'Матовый сланцево-серый с геометрическими узорами из серебристого хрома. Четкие архитектурные линии встречаются с мягкими серыми тонами для создания современной городской эстетики.',
        'Gold glitter with Swarovski crystal placement. The ultimate celebration nail — designed for moments when only the most dazzling will do.': 'Золотые блестки с размещением кристаллов Swarovski. Идеальные ногти для торжества — созданы для моментов, когда нужно только самое ослепительное.',
        'Dusty mauve with 3D gold chain embellishments. A bold, fashion-forward statement that bridges the gap between jewelry and nail art.': 'Пыльный лиловый с объемными золотыми украшениями в виде цепей. Смелое, ультрасовременное заявление, стирающее грань между ювелирными изделиями и нейл-артом.',
        'Teal base with silver chrome wave patterns. Fluid and dynamic, this design captures the motion of ocean waves in metallic form.': 'Бирюзовая база с волнообразными узорами из серебристого хрома. Текучий и динамичный, этот дизайн запечатлел движение океанских волн в металлической форме.',
        'Soft diffused aura gradient in peach and magenta. A deeply spiritual, glowing design that mimics the ethereal energy fields of the body.': 'Мягкий рассеянный градиент ауры в персиковых и пурпурных тонах. Глубоко духовный, светящийся дизайн, имитирующий эфирные энергетические поля тела.',
        'Black matte with gold studded geometric patterns. Powerful, confident, and unapologetically bold — for those who command the room.': 'Черный матовый с золотыми заклепками в геометрическом порядке. Мощный, уверенный и бескомпромиссно смелый — для тех, кто правит миром.',


        // Hero
        'h-title-art': 'The |Art| of',
        'h-title-precision': 'Precision.',
        'h-btn-explore': 'Исследовать ателье',
        'h-btn-about': 'О нас',
        'h-label-atelier': 'Цифровое ателье',
        'ed-discover': 'Откройте для себя совершенство',
        'ed-craft': 'Создайте свой стиль',
        'ed-book': 'Забронировать сейчас',
        'ed-related': 'Похожие статьи',

        // CTA
        'cta-title': 'Забронируйте встречу.',
        'cta-desc': 'Количество мест на этот сезон в нашей центральной студии ограничено.',
        'cta-btn': 'Забронировать сейчас',

        // Visual Break
        'vb-glass-title': 'Стеклянные ногти',
        'vb-glass-sub': 'Эффект стекла',
        'vb-chrome-title': 'Хром Арт',
        'vb-chrome-sub': 'Металлик серебро',
        'vb-3d-title': '3D · Шампань',
        'vb-3d-sub': 'Золотое шампанское',

        // Brief Intro
        'intro-text': 'REMY MUSE — современное нейл-ателье. Продумано до каждой детали. Создано для вас.',

        // Testimonials
        'review-role': 'Клиент',
        'review-1-quote': '"Тщательная и чистая работа. Я очень довольна своим новым маникюром."',
        'review-2-quote': '"Нежный и приятный персонал. Атмосфера очень расслабляющая."',
        'review-3-quote': '"Внимательное обслуживание, профессиональная консультация. Обязательно вернусь."',

        // Catalog
        'catalog-btn': 'Смотреть все меню →',
        'catalog-close': 'Закрыть',

        'nav-booking': 'Бронь',
        'vc-trending': 'Тренды',
        'vc-gallery-label': 'Портфолио',
        'vc-gallery-title': 'Галерея Дизайна',
        'vc-gallery-subtitle': 'Простые и чистые дизайны для будней и особых случаев.',
        'vc-no-match': 'Нет дизайнов, соответствующих вашему выбору.',
        'vc-latest-featured': 'Последние избранные работы',
        'vc-view-full': 'Смотреть всю галерею',
        'fa-call': 'Позвонить',
        'fa-book': 'Бронь',
        'bp-label': 'Инсайты',
        'bp-title': 'Инсайты',
        'bp-desc': 'Простые советы, тренды и идеи для ваших ногтей.',
        'bp-trending': 'Выбор редактора',
        'bp-view-all': 'Исследовать всю библиотеку',

        // Booking
        'ft-studio-desc': 'Nail — Shampoo — Foot Care Studio',
        'booking-err-fail': 'Не удалось создать бронирование',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("VN");

    const t = (key: string) => {
        const value = translations[language][key];
        return value !== undefined ? value : key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}

