"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "VN" | "EN" | "KR" | "CN" | "RU";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    VN: {
        'h-eyebrow': 'Luxury Nail Studio · Đà Nẵng',
        'h-sub': 'Service Menu · Bảng Dịch Vụ',
        's-muse-title': 'Làm móng tay & chân',
        's-muse-sub': 'Chăm sóc móng cơ bản',
        'h-quote': 'Nghệ thuật bắt nguồn từ sự <span>tận tâm</span>. Chúng tôi không chỉ thiết kế móng; chúng tôi trân trọng câu chuyện của bạn.',
        'h-scroll': 'Cuộn xuống',
        's1-title': 'Nail', 's1-sub': 'Dịch vụ móng tay',
        's2-title': 'Pedicure', 's2-sub': 'Chăm sóc móng chân',
        's3-title': 'Add-On', 's3-sub': 'Dịch vụ bổ sung',
        's4-title': 'Hair & Scalp', 's4-sub': 'Gội đầu dưỡng sinh',
        'g-manicure': 'Manicure · Chăm sóc móng',
        'g-enhance': 'Nail Enhancements · Đắp móng',
        'g-art': 'Nail Art',
        'art-note': 'Giá chưa bao gồm sơn gel · Gel polish not included',
        'n-classic-vi': 'Chăm sóc móng cơ bản', 'd-classic': 'Cắt tỉa, dũa móng, chăm sóc da khóe, khăn nóng, thoa kem tay.',
        'n-deluxemani-vi': 'Chăm sóc móng cao cấp', 'd-deluxemani': 'Cắt tỉa, dũa móng, chăm sóc da khóe, gel mặt nạ làm mát, massage tay với kem dưỡng.',
        'n-regpol-vi': 'Sơn thường', 'n-gelpol-vi': 'Sơn gel',
        'n-gelx-vi': 'Uốn móng Gel-X', 'n-buildergel-vi': 'Đắp gel / Tap gel',
        'n-acrylic-vi': 'Đắp bột Acrylic', 'n-refill-vi': 'Bảo dưỡng Acrylic / Builder Gel',
        'n-dual-vi': 'Đắp Dual Form', 'n-biab-vi': 'Đắp BIAB',
        'n-french-vi': 'French Tip', 'n-ombre-vi': 'Ombre', 'n-chrome-vi': 'Chrome / Crom',
        'n-cateye-vi': 'Cat Eye gel', 'n-minimal-vi': 'Nail Art tối giản',
        'n-3d-vi': 'Nghệ thuật 3D / Đính đá / Charm', 'n-custom-vi': 'Vẽ tay / Thiết kế riêng',
        's-essential-title': 'Thiết kế cơ bản', 's-essential-sub': 'Mẫu cơ bản',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Full French Tip', 'n-full-ombre': 'Full Ombre',
        'n-full-chrome': 'Full Chrome', 'n-full-cateye': 'Full Cat eye',
        's-bespoke-title': 'Thiết kế riêng', 's-bespoke-sub': 'Mẫu thiết kế theo yêu cầu',
        'n-bespoke-items': 'Mẫu vẽ tay, thiết kế riêng', 'p-on-request': 'Báo giá theo mẫu',
        'pu1': '/ móng', 'pu2': '/ móng', 'pu3': '/ móng',
        'n-classpedi-vi': 'Chăm sóc chân cơ bản', 'd-classpedi': 'Ngâm chân thảo dược, chà gót, tẩy da chết, cắt tỉa móng, chăm sóc da khóe, khăn nóng, thoa kem.',
        'n-deluxepedi-vi': 'Chăm sóc chân cao cấp', 'd-deluxepedi': 'Bộ kit 4 bước Deluxe: chăm sóc da khóe, cắt tỉa móng, mặt nạ, massage chân.',
        'n-gelcolor-vi': 'Gel màu', 'n-regcolor-vi': 'Sơn thường',
        'n-remacrylic-vi': 'Tháo Acrylic / Gel-X', 'n-remgel-vi': 'Tháo sơn gel',
        'n-classic30-vi': 'Gội đầu cơ bản', 'd-classic30': 'Massage đầu khô, gội dưỡng sinh bằng dầu thảo dược 2 lần, massage đầu tóc & gội xả thảo dược, massage vùng cổ vai gáy cơ bản.',
        'n-deluxe70-vi': 'Gội đầu thư giãn', 'n-luxury90-vi': 'Gội đầu chuyên sâu',
        'sum-d70-txt': 'Xem quy trình 16 bước', 'sum-l90-txt': 'Xem quy trình 19 bước',
        'ft-tagline': 'Nail Studio · Đà Nẵng',
        'ft-note': 'Giá chưa bao gồm thuế<br>Prices subject to change without notice<br>© REMY MUSE Nail Studio',
    },
    EN: {
        'h-eyebrow': 'Luxury Nail Studio · Da Nang',
        'h-sub': 'Service Menu',
        's-muse-title': 'Manicure & Pedicure',
        's-muse-sub': 'Basic nail care',
        'h-quote': 'Artistry inspired by <span>care</span>. We don’t just design nails; we cherish your story.',
        'h-scroll': 'Scroll',
        's1-title': 'Nail Services', 's1-sub': 'Nail Care',
        's2-title': 'Pedicure', 's2-sub': 'Foot Care',
        's3-title': 'Add-On', 's3-sub': 'Optional Extras',
        's4-title': 'Hair & Scalp', 's4-sub': 'Herbal Shampoo',
        'g-manicure': 'Manicure', 'g-enhance': 'Nail Enhancements', 'g-art': 'Nail Art',
        'art-note': 'Gel polish not included in Nail Art prices',
        'n-classic-vi': 'Classic Manicure', 'd-classic': 'Nail trimming & shaping, cuticle grooming, hot towel, cream hand application.',
        'n-deluxemani-vi': 'Deluxe Manicure', 'd-deluxemani': 'Nail trimming & shaping, cuticle grooming, cooling gel mask, hand massage with cream.',
        'n-regpol-vi': 'Regular Polish', 'n-gelpol-vi': 'Gel Polish',
        'n-gelx-vi': 'Gel-X Full Set', 'n-buildergel-vi': 'Builder Gel Full Set',
        'n-acrylic-vi': 'Acrylic Full Set', 'n-refill-vi': 'Acrylic / Builder Gel Refill',
        'n-dual-vi': 'Dual Form Full Set', 'n-biab-vi': 'BIAB Overlay',
        'n-french-vi': 'French Tip', 'n-ombre-vi': 'Ombre', 'n-chrome-vi': 'Chrome Powder',
        'n-cateye-vi': 'Cat Eye', 'n-minimal-vi': 'Minimal Nail Art',
        'n-3d-vi': '3D Art / Rhinestone / Charm', 'n-custom-vi': 'Custom / Hand-Painted Design',
        's-essential-title': 'Basic Designs', 's-essential-sub': 'Core Artistry',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Full French Tip', 'n-full-ombre': 'Full Ombre',
        'n-full-chrome': 'Full Chrome', 'n-full-cateye': 'Full Cat Eye',
        's-bespoke-title': 'Custom Design', 's-bespoke-sub': 'Custom Artistry',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': 'Price on request',
        'pu1': '/ nail', 'pu2': '/ nail', 'pu3': '/ nail',
        'n-classpedi-vi': 'Classic Pedicure', 'd-classpedi': 'Herbal foot soak, heel scrub, exfoliation, nail trimming, cuticle grooming, hot towel, cream.',
        'n-deluxepedi-vi': 'Deluxe Pedicure', 'd-deluxepedi': '4-step deluxe kit: cuticle care, trimming, mask, foot massage.',
        'n-gelcolor-vi': 'Gel Color', 'n-regcolor-vi': 'Regular Color',
        'n-remacrylic-vi': 'Acrylic / Gel-X Removal', 'n-remgel-vi': 'Gel Color Removal',
        'n-classic30-vi': 'Classic Shampoo', 'd-classic30': 'Dry scalp massage, double herbal shampoo, herbal conditioner massage, basic neck & shoulder massage.',
        'n-deluxe70-vi': 'Deluxe Shampoo', 'n-luxury90-vi': 'Luxury Shampoo',
        'sum-d70-txt': 'View 16-step process', 'sum-l90-txt': 'View 19-step process',
        'ft-tagline': 'Nail Studio · Da Nang',
        'ft-note': 'Prices exclusive of tax<br>Subject to change without notice<br>© REMY MUSE Nail Studio',
    },
    KR: {
        'h-eyebrow': '럭셔리 네일 스튜디오 · 다낭',
        'h-sub': '서비스 메뉴',
        's-muse-title': 'The Muse Sculpt',
        's-muse-sub': '아키텍처 매니큐어 - 페디큐어',
        'h-quote': '예술성은 <span>정성</span>에서 시작됩니다. 우리는 단순한 네일 디자인을 넘어, 당신의 이야기를 소중히 담아냅니다.',
        'h-scroll': '스크롤',
        's1-title': '네일 서비스', 's1-sub': '네일 케어',
        's2-title': '페디큐어', 's2-sub': '발 관리',
        's3-title': '추가 서비스', 's3-sub': '옵션',
        's4-title': '헤어 & 두피', 's4-sub': '허브 샴푸',
        'g-manicure': '매니큐어', 'g-enhance': '네일 연장', 'g-art': '네일 아트',
        'art-note': '네일 아트 가격에 젤 폴리시는 미포함',
        'n-classic-vi': '클래식 매니큐어', 'd-classic': '손톱 정리·모양잡기, 큐티클 케어, 핫 타월, 핸드크림.',
        'n-deluxemani-vi': '디럭스 매니큐어', 'd-deluxemani': '손톱 정리·모양잡기, 큐티클 케어, 쿨링 젤 마스크, 핸드 마사지.',
        'n-regpol-vi': '일반 폴리시', 'n-gelpol-vi': '젤 폴리시',
        'n-gelx-vi': 'Gel-X 풀세트', 'n-buildergel-vi': '빌더 젤 풀세트',
        'n-acrylic-vi': '아크릴 풀세트', 'n-refill-vi': '아크릴/빌더젤 리필',
        'n-dual-vi': '듀얼 폼 풀세트', 'n-biab-vi': 'BIAB 오버레이',
        'n-french-vi': '프렌치 팁', 'n-ombre-vi': '옴브레', 'n-chrome-vi': '크롬 파우더',
        'n-cateye-vi': '캣아이', 'n-minimal-vi': '미니멀 아트',
        'n-3d-vi': '3D아트/라인스톤/참', 'n-custom-vi': '커스텀/핸드페인팅',
        's-essential-title': 'Essential Designs', 's-essential-sub': '코어 네일 아트',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': '풀 프렌치 팁 (Full French Tip)', 'n-full-ombre': '풀 옴브레 (Full Ombre)',
        'n-full-chrome': '풀 크롬 (Full Chrome)', 'n-full-cateye': '풀 캣아이 (Full Cat Eye)',
        's-bespoke-title': 'Bespoke', 's-bespoke-sub': '커스텀 아트',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': '디자인별 별도 문의',
        'pu1': '/ 손가락', 'pu2': '/ 손가락', 'pu3': '/ 손가락',
        'n-classpedi-vi': '클래식 페디큐어', 'd-classpedi': '허브 족욕, 굳은살 제거, 각질 제거, 손발톱 정리, 큐티클 케어, 핫 타월, 크림.',
        'n-deluxepedi-vi': '디럭스 페디큐어', 'd-deluxepedi': '4단계 디럭스 키트: 큐티클 케어, 정리, 마스크, 발 마사지.',
        'n-gelcolor-vi': '젤 컬러', 'n-regcolor-vi': '일반 컬러',
        'n-remacrylic-vi': '아크릴/Gel-X 제거', 'n-remgel-vi': '젤 컬러 제거',
        'n-classic30-vi': '클래식 샴푸', 'd-classic30': '드라이 두피 마사지, 허브 오일 샴푸 2회, 허브 컨디셔너 마사지, 기본 목·어깨 마사지.',
        'n-deluxe70-vi': '디럭스 샴푸', 'n-luxury90-vi': '럭셔리 샴푸',
        'sum-d70-txt': '16단계 과정 보기', 'sum-l90-txt': '19단계 과정 보기',
        'ft-tagline': 'Nail Studio · 다낭',
        'ft-note': '가격은 세금 미포함<br>사전 공지 없이 변경 가능<br>© REMY MUSE Nail Studio',
    },
    CN: {
        'h-eyebrow': '奢华美甲工作室 · 岘港',
        'h-sub': '服务菜单',
        's-muse-title': 'The Muse Sculpt',
        's-muse-sub': '建筑美甲 - 足部护理',
        'h-quote': '艺境源于<span>关怀</span>。我们不仅在设计美甲，更在聆听并珍视您的故事。',
        'h-scroll': '向下滚动',
        's1-title': '美甲服务', 's1-sub': '指甲护理',
        's2-title': '足部护理', 's2-sub': '脚部护理',
        's3-title': '附加服务', 's3-sub': '可选附加',
        's4-title': '头发与头皮', 's4-sub': '草本洗发',
        'g-manicure': '美甲', 'g-enhance': '延甲', 'g-art': '美甲艺术',
        'art-note': '美甲艺术价格不含凝胶指甲油',
        'n-classic-vi': '经典美甲', 'd-classic': '修剪定型、护理甲皮、热毛巾、护手霜。',
        'n-deluxemani-vi': '豪华美甲', 'd-deluxemani': '修剪定型、护理甲皮、冷却凝胶面膜、护手霜手部按摩。',
        'n-regpol-vi': '普通指甲油', 'n-gelpol-vi': '凝胶指甲油',
        'n-gelx-vi': 'Gel-X全套', 'n-buildergel-vi': '构建凝胶全套',
        'n-acrylic-vi': '丙烯酸全套', 'n-refill-vi': '丙烯酸/构建凝胶补充',
        'n-dual-vi': '双模具全套', 'n-biab-vi': 'BIAB覆盖',
        'n-french-vi': '法式美甲', 'n-ombre-vi': '渐变色', 'n-chrome-vi': '镭射粉',
        'n-cateye-vi': '猫眼', 'n-minimal-vi': '简约美甲',
        'n-3d-vi': '3D艺术/水钻/吊坠', 'n-custom-vi': '手绘定制设计',
        's-essential-title': 'Essential Designs', 's-essential-sub': '核心美甲艺术',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': '全手法式 (Full French Tip)', 'n-full-ombre': '全手渐变 (Full Ombre)',
        'n-full-chrome': '全手魔镜粉 (Full Chrome)', 'n-full-cateye': '全手猫眼 (Full Cat Eye)',
        's-bespoke-title': 'Bespoke', 's-bespoke-sub': '定制美甲',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': '按设计报价',
        'pu1': '/ 指', 'pu2': '/ 指', 'pu3': '/ 指',
        'n-classpedi-vi': '经典足部护理', 'd-classpedi': '草本泡脚、去除老茧、去角质、修剪指甲、护理甲皮、热毛巾、涂霜。',
        'n-deluxepedi-vi': '豪华足部护理', 'd-deluxepedi': '4步豪华套装：护甲皮、修剪、面膜、足部按摩。',
        'n-gelcolor-vi': '凝胶颜色', 'n-regcolor-vi': '普通颜色',
        'n-remacrylic-vi': '卸除丙烯酸/Gel-X', 'n-remgel-vi': '卸除凝胶',
        'n-classic30-vi': '经典洗发', 'd-classic30': '干式头皮按摩，草本油洗发两次，草本护发素按摩，基础颈肩按摩。',
        'n-deluxe70-vi': '豪华洗发', 'n-luxury90-vi': '奢华洗发',
        'sum-d70-txt': '查看16步流程', 'sum-l90-txt': '查看19步流程',
        'ft-tagline': 'Nail Studio · 岘港',
        'ft-note': '价格不含税<br>如有变动恕不另行通知<br>© REMY MUSE Nail Studio',
    },
    RU: {
        'h-eyebrow': 'Люкс Нейл Студио · Да-Нанг',
        'h-sub': 'Меню услуг',
        's-muse-title': 'The Muse Sculpt',
        's-muse-sub': 'Архитектурный Маникюр - Педикюр',
        'h-quote': 'Искусство, рожденное из <span>заботы</span>. Мы не просто создаем дизайн ногтей — мы дорожим вашей историей.',
        'h-scroll': 'Вниз',
        's1-title': 'Ногтевой сервис', 's1-sub': 'Уход за ногтями',
        's2-title': 'Педикюр', 's2-sub': 'Уход за ногами',
        's3-title': 'Дополнительные', 's3-sub': 'Дополнения',
        's4-title': 'Волосы и кожа', 's4-sub': 'Травяной шампунь',
        'g-manicure': 'Маникюр', 'g-enhance': 'Наращивание ногтей', 'g-art': 'Дизайн ногтей',
        'art-note': 'Цены на дизайн не включают гель-лак',
        'n-classic-vi': 'Классический маникюр', 'd-classic': 'Обрезка и форма, уход за кутикулой, горячее полотенце, крем для рук.',
        'n-deluxemani-vi': 'Делюкс маникюр', 'd-deluxemani': 'Обрезка, уход за кутикулой, охлаждающая гель-маска, массаж рук с кремом.',
        'n-regpol-vi': 'Обычный лак', 'n-gelpol-vi': 'Гель-лак',
        'n-gelx-vi': 'Гель-Х полный набор', 'n-buildergel-vi': 'Билдер-гель полный набор',
        'n-acrylic-vi': 'Акрил полный набор', 'n-refill-vi': 'Акрил/билдер-гель рефил',
        'n-dual-vi': 'Дуал форм полный набор', 'n-biab-vi': 'BIAB оверлей',
        'n-french-vi': 'Французский маникюр', 'n-ombre-vi': 'Омбре', 'n-chrome-vi': 'Хромовый порошок',
        'n-cateye-vi': 'Кошачий глаз', 'n-minimal-vi': 'Минималистичный дизайн',
        'n-3d-vi': '3D-арт/стразы/шармы', 'n-custom-vi': 'Роспись ногтей на заказ',
        's-essential-title': 'Essential Designs', 's-essential-sub': 'Базовый дизайн',
        'n-essential-items': 'Full French Tip / Ombre / Chrome / Cat eye',
        'n-full-french': 'Френч (все ногти)', 'n-full-ombre': 'Омбре (все ногти)',
        'n-full-chrome': 'Втирка (все ногти)', 'n-full-cateye': 'Кошачий глаз (все ногти)',
        's-bespoke-title': 'Bespoke', 's-bespoke-sub': 'Индивидуальный дизайн',
        'n-bespoke-items': 'Custom, hand-painted sets', 'p-on-request': 'Цена по запросу',
        'pu1': '/ ноготь', 'pu2': '/ ноготь', 'pu3': '/ ноготь',
        'n-classpedi-vi': 'Классический педикюр', 'd-classpedi': 'Травяная ванночка, пилинг, скраб, обрезка, уход за кутикулой, горячее полотенце, крем.',
        'n-deluxepedi-vi': 'Делюкс педикюр', 'd-deluxepedi': '4-шаговый набор Deluxe: уход за кутикулой, обрезка, маска, массаж ног.',
        'n-gelcolor-vi': 'Гель-цвет', 'n-regcolor-vi': 'Обычный цвет',
        'n-remacrylic-vi': 'Снятие акрила/Гель-Х', 'n-remgel-vi': 'Снятие гель-лака',
        'n-classic30-vi': 'Классический шампунь', 'd-classic30': 'Сухой массаж кожи головы, двойное мытьё с травяным маслом, массаж с кондиционером, массаж шеи и плеч.',
        'n-deluxe70-vi': 'Делюкс шампунь', 'n-luxury90-vi': 'Люкс шампунь',
        'sum-d70-txt': 'Посмотреть 16 шагов', 'sum-l90-txt': 'Посмотреть 19 шагов',
        'ft-tagline': 'Nail Studio · Да-Нанг',
        'ft-note': 'Цены без учёта налогов<br>Возможны изменения без предупреждения<br>© REMY MUSE Nail Studio',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("VN");

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}

